// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="des_encrypt_des_encrypt,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.723857,HLS_SYN_LAT=16,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1907,HLS_SYN_LUT=36839,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module des_encrypt (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        plaintext,
        key,
        ciphertext,
        ciphertext_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] plaintext;
input  [63:0] key;
output  [63:0] ciphertext;
output   ciphertext_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ciphertext_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] plaintext_read_reg_162;
reg   [47:0] subkeys_reg_167;
reg   [47:0] subkeys_1_reg_172;
reg   [47:0] subkeys_2_reg_177;
reg   [47:0] subkeys_3_reg_182;
reg   [47:0] subkeys_4_reg_187;
reg   [47:0] subkeys_5_reg_192;
reg   [47:0] subkeys_6_reg_197;
reg   [47:0] subkeys_7_reg_202;
reg   [47:0] subkeys_8_reg_207;
reg   [47:0] subkeys_9_reg_212;
reg   [47:0] subkeys_10_reg_217;
reg   [47:0] subkeys_11_reg_222;
reg   [47:0] subkeys_12_reg_227;
reg   [47:0] subkeys_13_reg_232;
reg   [47:0] subkeys_14_reg_237;
reg   [47:0] subkeys_15_reg_242;
wire    call_ret_generate_subkeys_fu_53_ap_ready;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_0;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_1;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_2;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_3;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_4;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_5;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_6;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_7;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_8;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_9;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_10;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_11;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_12;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_13;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_14;
wire   [47:0] call_ret_generate_subkeys_fu_53_ap_return_15;
wire    grp_des_core_fu_59_ap_start;
wire    grp_des_core_fu_59_ap_done;
wire    grp_des_core_fu_59_ap_idle;
wire    grp_des_core_fu_59_ap_ready;
wire   [63:0] grp_des_core_fu_59_ap_return;
reg    grp_des_core_fu_59_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_des_core_fu_59_ap_start_reg = 1'b0;
end

des_encrypt_generate_subkeys call_ret_generate_subkeys_fu_53(
    .ap_ready(call_ret_generate_subkeys_fu_53_ap_ready),
    .key(key),
    .ap_return_0(call_ret_generate_subkeys_fu_53_ap_return_0),
    .ap_return_1(call_ret_generate_subkeys_fu_53_ap_return_1),
    .ap_return_2(call_ret_generate_subkeys_fu_53_ap_return_2),
    .ap_return_3(call_ret_generate_subkeys_fu_53_ap_return_3),
    .ap_return_4(call_ret_generate_subkeys_fu_53_ap_return_4),
    .ap_return_5(call_ret_generate_subkeys_fu_53_ap_return_5),
    .ap_return_6(call_ret_generate_subkeys_fu_53_ap_return_6),
    .ap_return_7(call_ret_generate_subkeys_fu_53_ap_return_7),
    .ap_return_8(call_ret_generate_subkeys_fu_53_ap_return_8),
    .ap_return_9(call_ret_generate_subkeys_fu_53_ap_return_9),
    .ap_return_10(call_ret_generate_subkeys_fu_53_ap_return_10),
    .ap_return_11(call_ret_generate_subkeys_fu_53_ap_return_11),
    .ap_return_12(call_ret_generate_subkeys_fu_53_ap_return_12),
    .ap_return_13(call_ret_generate_subkeys_fu_53_ap_return_13),
    .ap_return_14(call_ret_generate_subkeys_fu_53_ap_return_14),
    .ap_return_15(call_ret_generate_subkeys_fu_53_ap_return_15),
    .ap_rst(ap_rst)
);

des_encrypt_des_core grp_des_core_fu_59(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_des_core_fu_59_ap_start),
    .ap_done(grp_des_core_fu_59_ap_done),
    .ap_idle(grp_des_core_fu_59_ap_idle),
    .ap_ready(grp_des_core_fu_59_ap_ready),
    .input_r(plaintext_read_reg_162),
    .subkeys_0_val(subkeys_reg_167),
    .subkeys_1_val(subkeys_1_reg_172),
    .subkeys_2_val(subkeys_2_reg_177),
    .subkeys_3_val(subkeys_3_reg_182),
    .subkeys_4_val(subkeys_4_reg_187),
    .subkeys_5_val(subkeys_5_reg_192),
    .subkeys_6_val(subkeys_6_reg_197),
    .subkeys_7_val(subkeys_7_reg_202),
    .subkeys_8_val(subkeys_8_reg_207),
    .subkeys_9_val(subkeys_9_reg_212),
    .subkeys_10_val(subkeys_10_reg_217),
    .subkeys_11_val(subkeys_11_reg_222),
    .subkeys_12_val(subkeys_12_reg_227),
    .subkeys_13_val(subkeys_13_reg_232),
    .subkeys_14_val(subkeys_14_reg_237),
    .subkeys_15_val(subkeys_15_reg_242),
    .ap_return(grp_des_core_fu_59_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_des_core_fu_59_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_des_core_fu_59_ap_start_reg <= 1'b1;
        end else if ((grp_des_core_fu_59_ap_ready == 1'b1)) begin
            grp_des_core_fu_59_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        plaintext_read_reg_162 <= plaintext;
        subkeys_10_reg_217 <= call_ret_generate_subkeys_fu_53_ap_return_10;
        subkeys_11_reg_222 <= call_ret_generate_subkeys_fu_53_ap_return_11;
        subkeys_12_reg_227 <= call_ret_generate_subkeys_fu_53_ap_return_12;
        subkeys_13_reg_232 <= call_ret_generate_subkeys_fu_53_ap_return_13;
        subkeys_14_reg_237 <= call_ret_generate_subkeys_fu_53_ap_return_14;
        subkeys_15_reg_242 <= call_ret_generate_subkeys_fu_53_ap_return_15;
        subkeys_1_reg_172 <= call_ret_generate_subkeys_fu_53_ap_return_1;
        subkeys_2_reg_177 <= call_ret_generate_subkeys_fu_53_ap_return_2;
        subkeys_3_reg_182 <= call_ret_generate_subkeys_fu_53_ap_return_3;
        subkeys_4_reg_187 <= call_ret_generate_subkeys_fu_53_ap_return_4;
        subkeys_5_reg_192 <= call_ret_generate_subkeys_fu_53_ap_return_5;
        subkeys_6_reg_197 <= call_ret_generate_subkeys_fu_53_ap_return_6;
        subkeys_7_reg_202 <= call_ret_generate_subkeys_fu_53_ap_return_7;
        subkeys_8_reg_207 <= call_ret_generate_subkeys_fu_53_ap_return_8;
        subkeys_9_reg_212 <= call_ret_generate_subkeys_fu_53_ap_return_9;
        subkeys_reg_167 <= call_ret_generate_subkeys_fu_53_ap_return_0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_des_core_fu_59_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_des_core_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_des_core_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_des_core_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ciphertext_ap_vld = 1'b1;
    end else begin
        ciphertext_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_des_core_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ciphertext = grp_des_core_fu_59_ap_return;

assign grp_des_core_fu_59_ap_start = grp_des_core_fu_59_ap_start_reg;

endmodule //des_encrypt
