// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module des_encrypt_generate_subkeys (
        ap_ready,
        key,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_rst
);


output   ap_ready;
input  [63:0] key;
output  [47:0] ap_return_0;
output  [47:0] ap_return_1;
output  [47:0] ap_return_2;
output  [47:0] ap_return_3;
output  [47:0] ap_return_4;
output  [47:0] ap_return_5;
output  [47:0] ap_return_6;
output  [47:0] ap_return_7;
output  [47:0] ap_return_8;
output  [47:0] ap_return_9;
output  [47:0] ap_return_10;
output  [47:0] ap_return_11;
output  [47:0] ap_return_12;
output  [47:0] ap_return_13;
output  [47:0] ap_return_14;
output  [47:0] ap_return_15;
input   ap_rst;

wire   [0:0] tmp_14_fu_266_p3;
wire   [0:0] tmp_17_fu_290_p3;
wire   [0:0] tmp_11_fu_242_p3;
wire   [0:0] tmp_24_fu_346_p3;
wire   [0:0] tmp_1_fu_162_p3;
wire   [0:0] tmp_5_fu_194_p3;
wire   [0:0] tmp_3_fu_178_p3;
wire   [0:0] tmp_fu_154_p3;
wire   [0:0] tmp_15_fu_274_p3;
wire   [0:0] tmp_6_fu_202_p3;
wire   [0:0] tmp_21_fu_322_p3;
wire   [0:0] tmp_10_fu_234_p3;
wire   [0:0] tmp_23_fu_338_p3;
wire   [0:0] tmp_19_fu_306_p3;
reg   [1:0] tmp_55_fu_612_p4;
wire   [0:0] tmp_26_fu_362_p3;
wire   [1:0] tmp_s_fu_602_p4;
wire   [0:0] tmp_7_fu_210_p3;
wire   [0:0] tmp_27_fu_370_p3;
wire   [0:0] tmp_20_fu_314_p3;
wire   [0:0] tmp_13_fu_258_p3;
wire   [0:0] tmp_2_fu_170_p3;
wire   [0:0] tmp_41_fu_482_p3;
wire   [0:0] tmp_52_fu_570_p3;
wire   [0:0] tmp_31_fu_402_p3;
wire   [0:0] tmp_37_fu_450_p3;
wire   [0:0] tmp_47_fu_530_p3;
wire   [0:0] tmp_100_fu_594_p3;
wire   [0:0] tmp_30_fu_394_p3;
wire   [0:0] tmp_40_fu_474_p3;
wire   [0:0] tmp_51_fu_562_p3;
wire   [0:0] tmp_45_fu_514_p3;
wire   [0:0] tmp_33_fu_418_p3;
wire   [0:0] tmp_48_fu_538_p3;
wire   [0:0] tmp_44_fu_506_p3;
wire   [0:0] tmp_49_fu_546_p3;
wire   [0:0] tmp_39_fu_466_p3;
wire   [0:0] tmp_28_fu_378_p3;
wire   [0:0] tmp_34_fu_426_p3;
wire   [0:0] tmp_53_fu_578_p3;
wire   [0:0] tmp_46_fu_522_p3;
reg   [1:0] tmp_56_fu_622_p4;
wire   [0:0] tmp_36_fu_442_p3;
wire   [0:0] tmp_29_fu_386_p3;
wire   [0:0] tmp_32_fu_410_p3;
wire   [0:0] tmp_18_fu_298_p3;
wire   [0:0] tmp_12_fu_250_p3;
wire   [0:0] tmp_25_fu_354_p3;
wire   [0:0] tmp_4_fu_186_p3;
wire   [0:0] tmp_16_fu_282_p3;
wire   [0:0] tmp_22_fu_330_p3;
reg   [1:0] tmp_58_fu_736_p4;
wire   [1:0] tmp_57_fu_726_p4;
reg   [1:0] tmp_59_fu_746_p4;
wire   [0:0] tmp_42_fu_490_p3;
wire   [0:0] tmp_38_fu_458_p3;
wire   [0:0] tmp_50_fu_554_p3;
wire   [0:0] tmp_35_fu_434_p3;
wire   [0:0] tmp_54_fu_586_p3;
reg   [1:0] tmp_60_fu_756_p4;
wire   [0:0] tmp_8_fu_218_p3;
wire   [0:0] tmp_9_fu_226_p3;
reg   [1:0] tmp_62_fu_868_p4;
wire   [1:0] tmp_61_fu_858_p4;
reg   [1:0] tmp_63_fu_878_p4;
wire   [0:0] tmp_43_fu_498_p3;
reg   [1:0] tmp_66_fu_1002_p4;
wire   [1:0] tmp_64_fu_982_p4;
wire   [1:0] tmp_65_fu_992_p4;
reg   [1:0] tmp_69_fu_1124_p4;
wire   [1:0] tmp_67_fu_1104_p4;
reg   [1:0] tmp_70_fu_1134_p4;
wire   [1:0] tmp_68_fu_1114_p4;
reg   [1:0] tmp_73_fu_1254_p4;
wire   [1:0] tmp_72_fu_1244_p4;
reg   [1:0] tmp_74_fu_1264_p4;
reg   [1:0] tmp_71_fu_1234_p4;
reg   [1:0] tmp_77_fu_1384_p4;
wire   [1:0] tmp_76_fu_1374_p4;
reg   [1:0] tmp_78_fu_1394_p4;
reg   [1:0] tmp_75_fu_1364_p4;
reg   [1:0] tmp_80_fu_1506_p4;
reg   [1:0] tmp_81_fu_1516_p4;
reg   [1:0] tmp_79_fu_1496_p4;
reg   [1:0] tmp_83_fu_1630_p4;
reg   [1:0] tmp_82_fu_1620_p4;
reg   [1:0] tmp_84_fu_1732_p4;
reg   [1:0] tmp_85_fu_1836_p4;
wire   [1:0] tmp_87_fu_1950_p4;
reg   [1:0] tmp_88_fu_1960_p4;
reg   [1:0] tmp_89_fu_1970_p4;
reg   [1:0] tmp_86_fu_1940_p4;
wire   [1:0] tmp_91_fu_2082_p4;
reg   [1:0] tmp_92_fu_2092_p4;
reg   [1:0] tmp_90_fu_2072_p4;
wire   [1:0] tmp_93_fu_2196_p4;
reg   [1:0] tmp_94_fu_2206_p4;
wire   [1:0] tmp_95_fu_2308_p4;
reg   [1:0] tmp_96_fu_2318_p4;
reg   [1:0] tmp_98_fu_2432_p4;
wire   [1:0] tmp_97_fu_2422_p4;
wire   [47:0] subkey_fu_632_p46;
wire   [47:0] subkey_1_fu_766_p45;
wire   [47:0] subkey_2_fu_888_p46;
wire   [47:0] subkey_3_fu_1012_p45;
wire   [47:0] subkey_4_fu_1144_p44;
wire   [47:0] subkey_5_fu_1274_p44;
wire   [47:0] subkey_6_fu_1404_p45;
wire   [47:0] subkey_7_fu_1526_p46;
wire   [47:0] subkey_8_fu_1640_p45;
wire   [47:0] subkey_9_fu_1742_p46;
wire   [47:0] subkey_10_fu_1846_p46;
wire   [47:0] subkey_11_fu_1980_p45;
wire   [47:0] subkey_12_fu_2102_p46;
wire   [47:0] subkey_13_fu_2216_p45;
wire   [47:0] subkey_14_fu_2328_p46;
wire   [47:0] subkey_15_fu_2442_p46;

assign ap_ready = 1'b1;

assign subkey_10_fu_1846_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_4_fu_186_p3}, {tmp_7_fu_210_p3}}, {tmp_1_fu_162_p3}}, {tmp_14_fu_266_p3}}, {tmp_19_fu_306_p3}}, {tmp_23_fu_338_p3}}, {tmp_21_fu_322_p3}}, {tmp_18_fu_298_p3}}, {tmp_5_fu_194_p3}}, {tmp_24_fu_346_p3}}, {tmp_11_fu_242_p3}}, {tmp_fu_154_p3}}, {tmp_13_fu_258_p3}}, {tmp_9_fu_226_p3}}, {tmp_2_fu_170_p3}}, {tmp_22_fu_330_p3}}, {tmp_16_fu_282_p3}}, {tmp_26_fu_362_p3}}, {tmp_6_fu_202_p3}}, {tmp_80_fu_1506_p4}}, {tmp_10_fu_234_p3}}, {tmp_3_fu_178_p3}}, {tmp_20_fu_314_p3}}, {tmp_31_fu_402_p3}}, {tmp_42_fu_490_p3}}, {tmp_49_fu_546_p3}}, {tmp_100_fu_594_p3}}, {tmp_85_fu_1836_p4}}, {tmp_48_fu_538_p3}}, {tmp_30_fu_394_p3}}, {tmp_41_fu_482_p3}}, {tmp_35_fu_434_p3}}, {tmp_51_fu_562_p3}}, {tmp_38_fu_458_p3}}, {tmp_34_fu_426_p3}}, {tmp_39_fu_466_p3}}, {tmp_29_fu_386_p3}}, {tmp_46_fu_522_p3}}, {tmp_52_fu_570_p3}}, {tmp_43_fu_498_p3}}, {tmp_36_fu_442_p3}}, {tmp_79_fu_1496_p4}}, {tmp_54_fu_586_p3}}, {tmp_47_fu_530_p3}}, {tmp_50_fu_554_p3}};

assign subkey_11_fu_1980_p45 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_6_fu_202_p3}, {tmp_9_fu_226_p3}}, {tmp_3_fu_178_p3}}, {tmp_16_fu_282_p3}}, {tmp_21_fu_322_p3}}, {tmp_25_fu_354_p3}}, {tmp_23_fu_338_p3}}, {tmp_20_fu_314_p3}}, {tmp_7_fu_210_p3}}, {tmp_26_fu_362_p3}}, {tmp_13_fu_258_p3}}, {tmp_2_fu_170_p3}}, {tmp_15_fu_274_p3}}, {tmp_11_fu_242_p3}}, {tmp_4_fu_186_p3}}, {tmp_24_fu_346_p3}}, {tmp_18_fu_298_p3}}, {tmp_87_fu_1950_p4}}, {tmp_88_fu_1960_p4}}, {tmp_12_fu_250_p3}}, {tmp_5_fu_194_p3}}, {tmp_22_fu_330_p3}}, {tmp_33_fu_418_p3}}, {tmp_44_fu_506_p3}}, {tmp_51_fu_562_p3}}, {tmp_29_fu_386_p3}}, {tmp_89_fu_1970_p4}}, {tmp_50_fu_554_p3}}, {tmp_32_fu_410_p3}}, {tmp_43_fu_498_p3}}, {tmp_37_fu_450_p3}}, {tmp_53_fu_578_p3}}, {tmp_40_fu_474_p3}}, {tmp_36_fu_442_p3}}, {tmp_41_fu_482_p3}}, {tmp_31_fu_402_p3}}, {tmp_48_fu_538_p3}}, {tmp_54_fu_586_p3}}, {tmp_45_fu_514_p3}}, {tmp_38_fu_458_p3}}, {tmp_86_fu_1940_p4}}, {tmp_28_fu_378_p3}}, {tmp_49_fu_546_p3}}, {tmp_52_fu_570_p3}};

assign subkey_12_fu_2102_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_8_fu_218_p3}, {tmp_11_fu_242_p3}}, {tmp_5_fu_194_p3}}, {tmp_18_fu_298_p3}}, {tmp_23_fu_338_p3}}, {tmp_27_fu_370_p3}}, {tmp_25_fu_354_p3}}, {tmp_22_fu_330_p3}}, {tmp_9_fu_226_p3}}, {tmp_fu_154_p3}}, {tmp_15_fu_274_p3}}, {tmp_4_fu_186_p3}}, {tmp_17_fu_290_p3}}, {tmp_13_fu_258_p3}}, {tmp_6_fu_202_p3}}, {tmp_26_fu_362_p3}}, {tmp_20_fu_314_p3}}, {tmp_91_fu_2082_p4}}, {tmp_1_fu_162_p3}}, {tmp_21_fu_322_p3}}, {tmp_14_fu_266_p3}}, {tmp_7_fu_210_p3}}, {tmp_24_fu_346_p3}}, {tmp_35_fu_434_p3}}, {tmp_46_fu_522_p3}}, {tmp_53_fu_578_p3}}, {tmp_31_fu_402_p3}}, {tmp_92_fu_2092_p4}}, {tmp_52_fu_570_p3}}, {tmp_34_fu_426_p3}}, {tmp_45_fu_514_p3}}, {tmp_39_fu_466_p3}}, {tmp_100_fu_594_p3}}, {tmp_42_fu_490_p3}}, {tmp_38_fu_458_p3}}, {tmp_43_fu_498_p3}}, {tmp_33_fu_418_p3}}, {tmp_50_fu_554_p3}}, {tmp_28_fu_378_p3}}, {tmp_47_fu_530_p3}}, {tmp_40_fu_474_p3}}, {tmp_90_fu_2072_p4}}, {tmp_30_fu_394_p3}}, {tmp_51_fu_562_p3}}, {tmp_54_fu_586_p3}};

assign subkey_13_fu_2216_p45 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_10_fu_234_p3}, {tmp_13_fu_258_p3}}, {tmp_7_fu_210_p3}}, {tmp_20_fu_314_p3}}, {tmp_25_fu_354_p3}}, {tmp_1_fu_162_p3}}, {tmp_27_fu_370_p3}}, {tmp_24_fu_346_p3}}, {tmp_11_fu_242_p3}}, {tmp_2_fu_170_p3}}, {tmp_17_fu_290_p3}}, {tmp_6_fu_202_p3}}, {tmp_19_fu_306_p3}}, {tmp_15_fu_274_p3}}, {tmp_59_fu_746_p4}}, {tmp_22_fu_330_p3}}, {tmp_93_fu_2196_p4}}, {tmp_3_fu_178_p3}}, {tmp_23_fu_338_p3}}, {tmp_16_fu_282_p3}}, {tmp_9_fu_226_p3}}, {tmp_26_fu_362_p3}}, {tmp_37_fu_450_p3}}, {tmp_48_fu_538_p3}}, {tmp_100_fu_594_p3}}, {tmp_33_fu_418_p3}}, {tmp_60_fu_756_p4}}, {tmp_54_fu_586_p3}}, {tmp_36_fu_442_p3}}, {tmp_47_fu_530_p3}}, {tmp_41_fu_482_p3}}, {tmp_29_fu_386_p3}}, {tmp_44_fu_506_p3}}, {tmp_40_fu_474_p3}}, {tmp_45_fu_514_p3}}, {tmp_35_fu_434_p3}}, {tmp_52_fu_570_p3}}, {tmp_30_fu_394_p3}}, {tmp_49_fu_546_p3}}, {tmp_42_fu_490_p3}}, {tmp_94_fu_2206_p4}}, {tmp_32_fu_410_p3}}, {tmp_53_fu_578_p3}}, {tmp_28_fu_378_p3}};

assign subkey_14_fu_2328_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_12_fu_250_p3}, {tmp_15_fu_274_p3}}, {tmp_9_fu_226_p3}}, {tmp_22_fu_330_p3}}, {tmp_27_fu_370_p3}}, {tmp_3_fu_178_p3}}, {tmp_1_fu_162_p3}}, {tmp_26_fu_362_p3}}, {tmp_13_fu_258_p3}}, {tmp_4_fu_186_p3}}, {tmp_19_fu_306_p3}}, {tmp_8_fu_218_p3}}, {tmp_21_fu_322_p3}}, {tmp_17_fu_290_p3}}, {tmp_63_fu_878_p4}}, {tmp_24_fu_346_p3}}, {tmp_95_fu_2308_p4}}, {tmp_5_fu_194_p3}}, {tmp_25_fu_354_p3}}, {tmp_18_fu_298_p3}}, {tmp_11_fu_242_p3}}, {tmp_fu_154_p3}}, {tmp_39_fu_466_p3}}, {tmp_50_fu_554_p3}}, {tmp_29_fu_386_p3}}, {tmp_35_fu_434_p3}}, {tmp_45_fu_514_p3}}, {tmp_53_fu_578_p3}}, {tmp_28_fu_378_p3}}, {tmp_38_fu_458_p3}}, {tmp_49_fu_546_p3}}, {tmp_43_fu_498_p3}}, {tmp_31_fu_402_p3}}, {tmp_46_fu_522_p3}}, {tmp_42_fu_490_p3}}, {tmp_47_fu_530_p3}}, {tmp_37_fu_450_p3}}, {tmp_54_fu_586_p3}}, {tmp_32_fu_410_p3}}, {tmp_51_fu_562_p3}}, {tmp_44_fu_506_p3}}, {tmp_96_fu_2318_p4}}, {tmp_34_fu_426_p3}}, {tmp_100_fu_594_p3}}, {tmp_30_fu_394_p3}};

assign subkey_15_fu_2442_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_13_fu_258_p3}, {tmp_16_fu_282_p3}}, {tmp_10_fu_234_p3}}, {tmp_23_fu_338_p3}}, {tmp_fu_154_p3}}, {tmp_4_fu_186_p3}}, {tmp_2_fu_170_p3}}, {tmp_27_fu_370_p3}}, {tmp_14_fu_266_p3}}, {tmp_5_fu_194_p3}}, {tmp_20_fu_314_p3}}, {tmp_9_fu_226_p3}}, {tmp_22_fu_330_p3}}, {tmp_18_fu_298_p3}}, {tmp_98_fu_2432_p4}}, {tmp_25_fu_354_p3}}, {tmp_97_fu_2422_p4}}, {tmp_6_fu_202_p3}}, {tmp_26_fu_362_p3}}, {tmp_19_fu_306_p3}}, {tmp_12_fu_250_p3}}, {tmp_1_fu_162_p3}}, {tmp_40_fu_474_p3}}, {tmp_51_fu_562_p3}}, {tmp_30_fu_394_p3}}, {tmp_36_fu_442_p3}}, {tmp_46_fu_522_p3}}, {tmp_54_fu_586_p3}}, {tmp_29_fu_386_p3}}, {tmp_39_fu_466_p3}}, {tmp_50_fu_554_p3}}, {tmp_44_fu_506_p3}}, {tmp_32_fu_410_p3}}, {tmp_47_fu_530_p3}}, {tmp_43_fu_498_p3}}, {tmp_48_fu_538_p3}}, {tmp_38_fu_458_p3}}, {tmp_100_fu_594_p3}}, {tmp_33_fu_418_p3}}, {tmp_52_fu_570_p3}}, {tmp_45_fu_514_p3}}, {tmp_92_fu_2092_p4}}, {tmp_35_fu_434_p3}}, {tmp_28_fu_378_p3}}, {tmp_31_fu_402_p3}};

assign subkey_1_fu_766_p45 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_15_fu_274_p3}, {tmp_18_fu_298_p3}}, {tmp_12_fu_250_p3}}, {tmp_25_fu_354_p3}}, {tmp_2_fu_170_p3}}, {tmp_6_fu_202_p3}}, {tmp_4_fu_186_p3}}, {tmp_1_fu_162_p3}}, {tmp_16_fu_282_p3}}, {tmp_7_fu_210_p3}}, {tmp_22_fu_330_p3}}, {tmp_11_fu_242_p3}}, {tmp_24_fu_346_p3}}, {tmp_20_fu_314_p3}}, {tmp_58_fu_736_p4}}, {tmp_27_fu_370_p3}}, {tmp_57_fu_726_p4}}, {tmp_59_fu_746_p4}}, {tmp_21_fu_322_p3}}, {tmp_14_fu_266_p3}}, {tmp_3_fu_178_p3}}, {tmp_42_fu_490_p3}}, {tmp_53_fu_578_p3}}, {tmp_32_fu_410_p3}}, {tmp_38_fu_458_p3}}, {tmp_48_fu_538_p3}}, {tmp_28_fu_378_p3}}, {tmp_31_fu_402_p3}}, {tmp_41_fu_482_p3}}, {tmp_52_fu_570_p3}}, {tmp_46_fu_522_p3}}, {tmp_34_fu_426_p3}}, {tmp_49_fu_546_p3}}, {tmp_45_fu_514_p3}}, {tmp_50_fu_554_p3}}, {tmp_40_fu_474_p3}}, {tmp_29_fu_386_p3}}, {tmp_35_fu_434_p3}}, {tmp_54_fu_586_p3}}, {tmp_47_fu_530_p3}}, {tmp_60_fu_756_p4}}, {tmp_37_fu_450_p3}}, {tmp_30_fu_394_p3}}, {tmp_33_fu_418_p3}};

assign subkey_2_fu_888_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_17_fu_290_p3}, {tmp_20_fu_314_p3}}, {tmp_14_fu_266_p3}}, {tmp_27_fu_370_p3}}, {tmp_4_fu_186_p3}}, {tmp_8_fu_218_p3}}, {tmp_6_fu_202_p3}}, {tmp_3_fu_178_p3}}, {tmp_18_fu_298_p3}}, {tmp_9_fu_226_p3}}, {tmp_24_fu_346_p3}}, {tmp_13_fu_258_p3}}, {tmp_26_fu_362_p3}}, {tmp_22_fu_330_p3}}, {tmp_62_fu_868_p4}}, {tmp_1_fu_162_p3}}, {tmp_61_fu_858_p4}}, {tmp_63_fu_878_p4}}, {tmp_23_fu_338_p3}}, {tmp_16_fu_282_p3}}, {tmp_5_fu_194_p3}}, {tmp_44_fu_506_p3}}, {tmp_100_fu_594_p3}}, {tmp_34_fu_426_p3}}, {tmp_40_fu_474_p3}}, {tmp_50_fu_554_p3}}, {tmp_30_fu_394_p3}}, {tmp_33_fu_418_p3}}, {tmp_43_fu_498_p3}}, {tmp_54_fu_586_p3}}, {tmp_48_fu_538_p3}}, {tmp_36_fu_442_p3}}, {tmp_51_fu_562_p3}}, {tmp_47_fu_530_p3}}, {tmp_52_fu_570_p3}}, {tmp_42_fu_490_p3}}, {tmp_31_fu_402_p3}}, {tmp_37_fu_450_p3}}, {tmp_28_fu_378_p3}}, {tmp_49_fu_546_p3}}, {tmp_45_fu_514_p3}}, {tmp_53_fu_578_p3}}, {tmp_39_fu_466_p3}}, {tmp_32_fu_410_p3}}, {tmp_35_fu_434_p3}};

assign subkey_3_fu_1012_p45 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_19_fu_306_p3}, {tmp_22_fu_330_p3}}, {tmp_16_fu_282_p3}}, {tmp_1_fu_162_p3}}, {tmp_6_fu_202_p3}}, {tmp_10_fu_234_p3}}, {tmp_8_fu_218_p3}}, {tmp_5_fu_194_p3}}, {tmp_20_fu_314_p3}}, {tmp_11_fu_242_p3}}, {tmp_26_fu_362_p3}}, {tmp_15_fu_274_p3}}, {tmp_fu_154_p3}}, {tmp_24_fu_346_p3}}, {tmp_66_fu_1002_p4}}, {tmp_3_fu_178_p3}}, {tmp_64_fu_982_p4}}, {tmp_55_fu_612_p4}}, {tmp_25_fu_354_p3}}, {tmp_18_fu_298_p3}}, {tmp_7_fu_210_p3}}, {tmp_46_fu_522_p3}}, {tmp_29_fu_386_p3}}, {tmp_36_fu_442_p3}}, {tmp_42_fu_490_p3}}, {tmp_52_fu_570_p3}}, {tmp_32_fu_410_p3}}, {tmp_35_fu_434_p3}}, {tmp_45_fu_514_p3}}, {tmp_28_fu_378_p3}}, {tmp_50_fu_554_p3}}, {tmp_38_fu_458_p3}}, {tmp_65_fu_992_p4}}, {tmp_54_fu_586_p3}}, {tmp_44_fu_506_p3}}, {tmp_33_fu_418_p3}}, {tmp_39_fu_466_p3}}, {tmp_30_fu_394_p3}}, {tmp_51_fu_562_p3}}, {tmp_47_fu_530_p3}}, {tmp_100_fu_594_p3}}, {tmp_41_fu_482_p3}}, {tmp_34_fu_426_p3}}, {tmp_37_fu_450_p3}};

assign subkey_4_fu_1144_p44 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_21_fu_322_p3}, {tmp_24_fu_346_p3}}, {tmp_18_fu_298_p3}}, {tmp_3_fu_178_p3}}, {tmp_8_fu_218_p3}}, {tmp_12_fu_250_p3}}, {tmp_10_fu_234_p3}}, {tmp_7_fu_210_p3}}, {tmp_22_fu_330_p3}}, {tmp_13_fu_258_p3}}, {tmp_fu_154_p3}}, {tmp_17_fu_290_p3}}, {tmp_2_fu_170_p3}}, {tmp_26_fu_362_p3}}, {tmp_69_fu_1124_p4}}, {tmp_5_fu_194_p3}}, {tmp_67_fu_1104_p4}}, {tmp_70_fu_1134_p4}}, {tmp_27_fu_370_p3}}, {tmp_20_fu_314_p3}}, {tmp_9_fu_226_p3}}, {tmp_48_fu_538_p3}}, {tmp_31_fu_402_p3}}, {tmp_38_fu_458_p3}}, {tmp_44_fu_506_p3}}, {tmp_54_fu_586_p3}}, {tmp_34_fu_426_p3}}, {tmp_37_fu_450_p3}}, {tmp_47_fu_530_p3}}, {tmp_30_fu_394_p3}}, {tmp_52_fu_570_p3}}, {tmp_40_fu_474_p3}}, {tmp_68_fu_1114_p4}}, {tmp_28_fu_378_p3}}, {tmp_46_fu_522_p3}}, {tmp_35_fu_434_p3}}, {tmp_41_fu_482_p3}}, {tmp_32_fu_410_p3}}, {tmp_65_fu_992_p4}}, {tmp_29_fu_386_p3}}, {tmp_43_fu_498_p3}}, {tmp_36_fu_442_p3}}, {tmp_39_fu_466_p3}};

assign subkey_5_fu_1274_p44 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_23_fu_338_p3}, {tmp_26_fu_362_p3}}, {tmp_20_fu_314_p3}}, {tmp_5_fu_194_p3}}, {tmp_10_fu_234_p3}}, {tmp_14_fu_266_p3}}, {tmp_12_fu_250_p3}}, {tmp_9_fu_226_p3}}, {tmp_24_fu_346_p3}}, {tmp_15_fu_274_p3}}, {tmp_2_fu_170_p3}}, {tmp_19_fu_306_p3}}, {tmp_4_fu_186_p3}}, {tmp_fu_154_p3}}, {tmp_73_fu_1254_p4}}, {tmp_7_fu_210_p3}}, {tmp_72_fu_1244_p4}}, {tmp_74_fu_1264_p4}}, {tmp_1_fu_162_p3}}, {tmp_22_fu_330_p3}}, {tmp_11_fu_242_p3}}, {tmp_50_fu_554_p3}}, {tmp_33_fu_418_p3}}, {tmp_40_fu_474_p3}}, {tmp_46_fu_522_p3}}, {tmp_71_fu_1234_p4}}, {tmp_39_fu_466_p3}}, {tmp_49_fu_546_p3}}, {tmp_32_fu_410_p3}}, {tmp_54_fu_586_p3}}, {tmp_42_fu_490_p3}}, {tmp_29_fu_386_p3}}, {tmp_53_fu_578_p3}}, {tmp_30_fu_394_p3}}, {tmp_48_fu_538_p3}}, {tmp_37_fu_450_p3}}, {tmp_43_fu_498_p3}}, {tmp_34_fu_426_p3}}, {tmp_68_fu_1114_p4}}, {tmp_31_fu_402_p3}}, {tmp_45_fu_514_p3}}, {tmp_38_fu_458_p3}}, {tmp_41_fu_482_p3}};

assign subkey_6_fu_1404_p45 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_25_fu_354_p3}, {tmp_fu_154_p3}}, {tmp_22_fu_330_p3}}, {tmp_7_fu_210_p3}}, {tmp_12_fu_250_p3}}, {tmp_16_fu_282_p3}}, {tmp_14_fu_266_p3}}, {tmp_11_fu_242_p3}}, {tmp_26_fu_362_p3}}, {tmp_17_fu_290_p3}}, {tmp_4_fu_186_p3}}, {tmp_21_fu_322_p3}}, {tmp_6_fu_202_p3}}, {tmp_2_fu_170_p3}}, {tmp_77_fu_1384_p4}}, {tmp_9_fu_226_p3}}, {tmp_76_fu_1374_p4}}, {tmp_78_fu_1394_p4}}, {tmp_3_fu_178_p3}}, {tmp_24_fu_346_p3}}, {tmp_13_fu_258_p3}}, {tmp_52_fu_570_p3}}, {tmp_35_fu_434_p3}}, {tmp_42_fu_490_p3}}, {tmp_48_fu_538_p3}}, {tmp_75_fu_1364_p4}}, {tmp_41_fu_482_p3}}, {tmp_51_fu_562_p3}}, {tmp_34_fu_426_p3}}, {tmp_28_fu_378_p3}}, {tmp_44_fu_506_p3}}, {tmp_31_fu_402_p3}}, {tmp_100_fu_594_p3}}, {tmp_32_fu_410_p3}}, {tmp_50_fu_554_p3}}, {tmp_39_fu_466_p3}}, {tmp_45_fu_514_p3}}, {tmp_36_fu_442_p3}}, {tmp_29_fu_386_p3}}, {tmp_53_fu_578_p3}}, {tmp_33_fu_418_p3}}, {tmp_47_fu_530_p3}}, {tmp_40_fu_474_p3}}, {tmp_43_fu_498_p3}};

assign subkey_7_fu_1526_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_27_fu_370_p3}, {tmp_2_fu_170_p3}}, {tmp_24_fu_346_p3}}, {tmp_9_fu_226_p3}}, {tmp_14_fu_266_p3}}, {tmp_18_fu_298_p3}}, {tmp_16_fu_282_p3}}, {tmp_13_fu_258_p3}}, {tmp_fu_154_p3}}, {tmp_19_fu_306_p3}}, {tmp_6_fu_202_p3}}, {tmp_23_fu_338_p3}}, {tmp_8_fu_218_p3}}, {tmp_4_fu_186_p3}}, {tmp_80_fu_1506_p4}}, {tmp_11_fu_242_p3}}, {tmp_21_fu_322_p3}}, {tmp_1_fu_162_p3}}, {tmp_81_fu_1516_p4}}, {tmp_5_fu_194_p3}}, {tmp_26_fu_362_p3}}, {tmp_15_fu_274_p3}}, {tmp_54_fu_586_p3}}, {tmp_37_fu_450_p3}}, {tmp_44_fu_506_p3}}, {tmp_50_fu_554_p3}}, {tmp_79_fu_1496_p4}}, {tmp_43_fu_498_p3}}, {tmp_53_fu_578_p3}}, {tmp_36_fu_442_p3}}, {tmp_30_fu_394_p3}}, {tmp_46_fu_522_p3}}, {tmp_33_fu_418_p3}}, {tmp_29_fu_386_p3}}, {tmp_34_fu_426_p3}}, {tmp_52_fu_570_p3}}, {tmp_41_fu_482_p3}}, {tmp_47_fu_530_p3}}, {tmp_38_fu_458_p3}}, {tmp_31_fu_402_p3}}, {tmp_100_fu_594_p3}}, {tmp_35_fu_434_p3}}, {tmp_49_fu_546_p3}}, {tmp_42_fu_490_p3}}, {tmp_45_fu_514_p3}};

assign subkey_8_fu_1640_p45 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_fu_154_p3}, {tmp_3_fu_178_p3}}, {tmp_25_fu_354_p3}}, {tmp_10_fu_234_p3}}, {tmp_15_fu_274_p3}}, {tmp_19_fu_306_p3}}, {tmp_17_fu_290_p3}}, {tmp_14_fu_266_p3}}, {tmp_1_fu_162_p3}}, {tmp_20_fu_314_p3}}, {tmp_7_fu_210_p3}}, {tmp_24_fu_346_p3}}, {tmp_9_fu_226_p3}}, {tmp_5_fu_194_p3}}, {tmp_83_fu_1630_p4}}, {tmp_12_fu_250_p3}}, {tmp_22_fu_330_p3}}, {tmp_2_fu_170_p3}}, {tmp_73_fu_1254_p4}}, {tmp_6_fu_202_p3}}, {tmp_27_fu_370_p3}}, {tmp_16_fu_282_p3}}, {tmp_100_fu_594_p3}}, {tmp_38_fu_458_p3}}, {tmp_45_fu_514_p3}}, {tmp_51_fu_562_p3}}, {tmp_82_fu_1620_p4}}, {tmp_44_fu_506_p3}}, {tmp_54_fu_586_p3}}, {tmp_37_fu_450_p3}}, {tmp_31_fu_402_p3}}, {tmp_47_fu_530_p3}}, {tmp_34_fu_426_p3}}, {tmp_30_fu_394_p3}}, {tmp_35_fu_434_p3}}, {tmp_53_fu_578_p3}}, {tmp_42_fu_490_p3}}, {tmp_48_fu_538_p3}}, {tmp_39_fu_466_p3}}, {tmp_32_fu_410_p3}}, {tmp_71_fu_1234_p4}}, {tmp_50_fu_554_p3}}, {tmp_43_fu_498_p3}}, {tmp_46_fu_522_p3}};

assign subkey_9_fu_1742_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_2_fu_170_p3}, {tmp_5_fu_194_p3}}, {tmp_27_fu_370_p3}}, {tmp_12_fu_250_p3}}, {tmp_17_fu_290_p3}}, {tmp_21_fu_322_p3}}, {tmp_19_fu_306_p3}}, {tmp_16_fu_282_p3}}, {tmp_3_fu_178_p3}}, {tmp_22_fu_330_p3}}, {tmp_9_fu_226_p3}}, {tmp_26_fu_362_p3}}, {tmp_11_fu_242_p3}}, {tmp_7_fu_210_p3}}, {tmp_fu_154_p3}}, {tmp_20_fu_314_p3}}, {tmp_14_fu_266_p3}}, {tmp_24_fu_346_p3}}, {tmp_4_fu_186_p3}}, {tmp_77_fu_1384_p4}}, {tmp_8_fu_218_p3}}, {tmp_1_fu_162_p3}}, {tmp_18_fu_298_p3}}, {tmp_29_fu_386_p3}}, {tmp_40_fu_474_p3}}, {tmp_47_fu_530_p3}}, {tmp_53_fu_578_p3}}, {tmp_84_fu_1732_p4}}, {tmp_46_fu_522_p3}}, {tmp_28_fu_378_p3}}, {tmp_39_fu_466_p3}}, {tmp_33_fu_418_p3}}, {tmp_49_fu_546_p3}}, {tmp_36_fu_442_p3}}, {tmp_32_fu_410_p3}}, {tmp_37_fu_450_p3}}, {tmp_100_fu_594_p3}}, {tmp_44_fu_506_p3}}, {tmp_50_fu_554_p3}}, {tmp_41_fu_482_p3}}, {tmp_34_fu_426_p3}}, {tmp_75_fu_1364_p4}}, {tmp_52_fu_570_p3}}, {tmp_45_fu_514_p3}}, {tmp_48_fu_538_p3}};

assign subkey_fu_632_p46 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_14_fu_266_p3}, {tmp_17_fu_290_p3}}, {tmp_11_fu_242_p3}}, {tmp_24_fu_346_p3}}, {tmp_1_fu_162_p3}}, {tmp_5_fu_194_p3}}, {tmp_3_fu_178_p3}}, {tmp_fu_154_p3}}, {tmp_15_fu_274_p3}}, {tmp_6_fu_202_p3}}, {tmp_21_fu_322_p3}}, {tmp_10_fu_234_p3}}, {tmp_23_fu_338_p3}}, {tmp_19_fu_306_p3}}, {tmp_55_fu_612_p4}}, {tmp_26_fu_362_p3}}, {tmp_s_fu_602_p4}}, {tmp_7_fu_210_p3}}, {tmp_27_fu_370_p3}}, {tmp_20_fu_314_p3}}, {tmp_13_fu_258_p3}}, {tmp_2_fu_170_p3}}, {tmp_41_fu_482_p3}}, {tmp_52_fu_570_p3}}, {tmp_31_fu_402_p3}}, {tmp_37_fu_450_p3}}, {tmp_47_fu_530_p3}}, {tmp_100_fu_594_p3}}, {tmp_30_fu_394_p3}}, {tmp_40_fu_474_p3}}, {tmp_51_fu_562_p3}}, {tmp_45_fu_514_p3}}, {tmp_33_fu_418_p3}}, {tmp_48_fu_538_p3}}, {tmp_44_fu_506_p3}}, {tmp_49_fu_546_p3}}, {tmp_39_fu_466_p3}}, {tmp_28_fu_378_p3}}, {tmp_34_fu_426_p3}}, {tmp_53_fu_578_p3}}, {tmp_46_fu_522_p3}}, {tmp_56_fu_622_p4}}, {tmp_36_fu_442_p3}}, {tmp_29_fu_386_p3}}, {tmp_32_fu_410_p3}};

assign tmp_100_fu_594_p3 = key[32'd60];

assign tmp_10_fu_234_p3 = key[32'd22];

assign tmp_11_fu_242_p3 = key[32'd30];

assign tmp_12_fu_250_p3 = key[32'd38];

assign tmp_13_fu_258_p3 = key[32'd46];

assign tmp_14_fu_266_p3 = key[32'd54];

assign tmp_15_fu_274_p3 = key[32'd62];

assign tmp_16_fu_282_p3 = key[32'd5];

assign tmp_17_fu_290_p3 = key[32'd13];

assign tmp_18_fu_298_p3 = key[32'd21];

assign tmp_19_fu_306_p3 = key[32'd29];

assign tmp_1_fu_162_p3 = key[32'd15];

assign tmp_20_fu_314_p3 = key[32'd37];

assign tmp_21_fu_322_p3 = key[32'd45];

assign tmp_22_fu_330_p3 = key[32'd53];

assign tmp_23_fu_338_p3 = key[32'd61];

assign tmp_24_fu_346_p3 = key[32'd4];

assign tmp_25_fu_354_p3 = key[32'd12];

assign tmp_26_fu_362_p3 = key[32'd20];

assign tmp_27_fu_370_p3 = key[32'd28];

assign tmp_28_fu_378_p3 = key[32'd1];

assign tmp_29_fu_386_p3 = key[32'd9];

assign tmp_2_fu_170_p3 = key[32'd23];

assign tmp_30_fu_394_p3 = key[32'd17];

assign tmp_31_fu_402_p3 = key[32'd25];

assign tmp_32_fu_410_p3 = key[32'd33];

assign tmp_33_fu_418_p3 = key[32'd41];

assign tmp_34_fu_426_p3 = key[32'd49];

assign tmp_35_fu_434_p3 = key[32'd57];

assign tmp_36_fu_442_p3 = key[32'd2];

assign tmp_37_fu_450_p3 = key[32'd10];

assign tmp_38_fu_458_p3 = key[32'd18];

assign tmp_39_fu_466_p3 = key[32'd26];

assign tmp_3_fu_178_p3 = key[32'd31];

assign tmp_40_fu_474_p3 = key[32'd34];

assign tmp_41_fu_482_p3 = key[32'd42];

assign tmp_42_fu_490_p3 = key[32'd50];

assign tmp_43_fu_498_p3 = key[32'd58];

assign tmp_44_fu_506_p3 = key[32'd3];

assign tmp_45_fu_514_p3 = key[32'd11];

assign tmp_46_fu_522_p3 = key[32'd19];

assign tmp_47_fu_530_p3 = key[32'd27];

assign tmp_48_fu_538_p3 = key[32'd35];

assign tmp_49_fu_546_p3 = key[32'd43];

assign tmp_4_fu_186_p3 = key[32'd39];

assign tmp_50_fu_554_p3 = key[32'd51];

assign tmp_51_fu_562_p3 = key[32'd59];

assign tmp_52_fu_570_p3 = key[32'd36];

assign tmp_53_fu_578_p3 = key[32'd44];

assign tmp_54_fu_586_p3 = key[32'd52];

integer ap_tvar_int_0;

always @ (key) begin
    for (ap_tvar_int_0 = 2 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 39 - 38) begin
            tmp_55_fu_612_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_55_fu_612_p4[ap_tvar_int_0] = key[39 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (key) begin
    for (ap_tvar_int_1 = 2 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 51 - 50) begin
            tmp_56_fu_622_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_56_fu_622_p4[ap_tvar_int_1] = key[51 - ap_tvar_int_1];
        end
    end
end

assign tmp_57_fu_726_p4 = {{key[14:13]}};

integer ap_tvar_int_2;

always @ (key) begin
    for (ap_tvar_int_2 = 2 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 47 - 46) begin
            tmp_58_fu_736_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_58_fu_736_p4[ap_tvar_int_2] = key[47 - ap_tvar_int_2];
        end
    end
end

integer ap_tvar_int_3;

always @ (key) begin
    for (ap_tvar_int_3 = 2 - 1; ap_tvar_int_3 >= 0; ap_tvar_int_3 = ap_tvar_int_3 - 1) begin
        if (ap_tvar_int_3 > 7 - 6) begin
            tmp_59_fu_746_p4[ap_tvar_int_3] = 1'b0;
        end else begin
            tmp_59_fu_746_p4[ap_tvar_int_3] = key[7 - ap_tvar_int_3];
        end
    end
end

assign tmp_5_fu_194_p3 = key[32'd47];

integer ap_tvar_int_4;

always @ (key) begin
    for (ap_tvar_int_4 = 2 - 1; ap_tvar_int_4 >= 0; ap_tvar_int_4 = ap_tvar_int_4 - 1) begin
        if (ap_tvar_int_4 > 59 - 58) begin
            tmp_60_fu_756_p4[ap_tvar_int_4] = 1'b0;
        end else begin
            tmp_60_fu_756_p4[ap_tvar_int_4] = key[59 - ap_tvar_int_4];
        end
    end
end

assign tmp_61_fu_858_p4 = {{key[30:29]}};

integer ap_tvar_int_5;

always @ (key) begin
    for (ap_tvar_int_5 = 2 - 1; ap_tvar_int_5 >= 0; ap_tvar_int_5 = ap_tvar_int_5 - 1) begin
        if (ap_tvar_int_5 > 63 - 62) begin
            tmp_62_fu_868_p4[ap_tvar_int_5] = 1'b0;
        end else begin
            tmp_62_fu_868_p4[ap_tvar_int_5] = key[63 - ap_tvar_int_5];
        end
    end
end

integer ap_tvar_int_6;

always @ (key) begin
    for (ap_tvar_int_6 = 2 - 1; ap_tvar_int_6 >= 0; ap_tvar_int_6 = ap_tvar_int_6 - 1) begin
        if (ap_tvar_int_6 > 23 - 22) begin
            tmp_63_fu_878_p4[ap_tvar_int_6] = 1'b0;
        end else begin
            tmp_63_fu_878_p4[ap_tvar_int_6] = key[23 - ap_tvar_int_6];
        end
    end
end

assign tmp_64_fu_982_p4 = {{key[46:45]}};

assign tmp_65_fu_992_p4 = {{key[44:43]}};

integer ap_tvar_int_7;

always @ (key) begin
    for (ap_tvar_int_7 = 2 - 1; ap_tvar_int_7 >= 0; ap_tvar_int_7 = ap_tvar_int_7 - 1) begin
        if (ap_tvar_int_7 > 14 - 13) begin
            tmp_66_fu_1002_p4[ap_tvar_int_7] = 1'b0;
        end else begin
            tmp_66_fu_1002_p4[ap_tvar_int_7] = key[14 - ap_tvar_int_7];
        end
    end
end

assign tmp_67_fu_1104_p4 = {{key[62:61]}};

assign tmp_68_fu_1114_p4 = {{key[60:59]}};

integer ap_tvar_int_8;

always @ (key) begin
    for (ap_tvar_int_8 = 2 - 1; ap_tvar_int_8 >= 0; ap_tvar_int_8 = ap_tvar_int_8 - 1) begin
        if (ap_tvar_int_8 > 30 - 29) begin
            tmp_69_fu_1124_p4[ap_tvar_int_8] = 1'b0;
        end else begin
            tmp_69_fu_1124_p4[ap_tvar_int_8] = key[30 - ap_tvar_int_8];
        end
    end
end

assign tmp_6_fu_202_p3 = key[32'd55];

integer ap_tvar_int_9;

always @ (key) begin
    for (ap_tvar_int_9 = 2 - 1; ap_tvar_int_9 >= 0; ap_tvar_int_9 = ap_tvar_int_9 - 1) begin
        if (ap_tvar_int_9 > 55 - 54) begin
            tmp_70_fu_1134_p4[ap_tvar_int_9] = 1'b0;
        end else begin
            tmp_70_fu_1134_p4[ap_tvar_int_9] = key[55 - ap_tvar_int_9];
        end
    end
end

integer ap_tvar_int_10;

always @ (key) begin
    for (ap_tvar_int_10 = 2 - 1; ap_tvar_int_10 >= 0; ap_tvar_int_10 = ap_tvar_int_10 - 1) begin
        if (ap_tvar_int_10 > 2 - 1) begin
            tmp_71_fu_1234_p4[ap_tvar_int_10] = 1'b0;
        end else begin
            tmp_71_fu_1234_p4[ap_tvar_int_10] = key[2 - ap_tvar_int_10];
        end
    end
end

assign tmp_72_fu_1244_p4 = {{key[13:12]}};

integer ap_tvar_int_11;

always @ (key) begin
    for (ap_tvar_int_11 = 2 - 1; ap_tvar_int_11 >= 0; ap_tvar_int_11 = ap_tvar_int_11 - 1) begin
        if (ap_tvar_int_11 > 46 - 45) begin
            tmp_73_fu_1254_p4[ap_tvar_int_11] = 1'b0;
        end else begin
            tmp_73_fu_1254_p4[ap_tvar_int_11] = key[46 - ap_tvar_int_11];
        end
    end
end

integer ap_tvar_int_12;

always @ (key) begin
    for (ap_tvar_int_12 = 2 - 1; ap_tvar_int_12 >= 0; ap_tvar_int_12 = ap_tvar_int_12 - 1) begin
        if (ap_tvar_int_12 > 6 - 5) begin
            tmp_74_fu_1264_p4[ap_tvar_int_12] = 1'b0;
        end else begin
            tmp_74_fu_1264_p4[ap_tvar_int_12] = key[6 - ap_tvar_int_12];
        end
    end
end

integer ap_tvar_int_13;

always @ (key) begin
    for (ap_tvar_int_13 = 2 - 1; ap_tvar_int_13 >= 0; ap_tvar_int_13 = ap_tvar_int_13 - 1) begin
        if (ap_tvar_int_13 > 18 - 17) begin
            tmp_75_fu_1364_p4[ap_tvar_int_13] = 1'b0;
        end else begin
            tmp_75_fu_1364_p4[ap_tvar_int_13] = key[18 - ap_tvar_int_13];
        end
    end
end

assign tmp_76_fu_1374_p4 = {{key[29:28]}};

integer ap_tvar_int_14;

always @ (key) begin
    for (ap_tvar_int_14 = 2 - 1; ap_tvar_int_14 >= 0; ap_tvar_int_14 = ap_tvar_int_14 - 1) begin
        if (ap_tvar_int_14 > 62 - 61) begin
            tmp_77_fu_1384_p4[ap_tvar_int_14] = 1'b0;
        end else begin
            tmp_77_fu_1384_p4[ap_tvar_int_14] = key[62 - ap_tvar_int_14];
        end
    end
end

integer ap_tvar_int_15;

always @ (key) begin
    for (ap_tvar_int_15 = 2 - 1; ap_tvar_int_15 >= 0; ap_tvar_int_15 = ap_tvar_int_15 - 1) begin
        if (ap_tvar_int_15 > 22 - 21) begin
            tmp_78_fu_1394_p4[ap_tvar_int_15] = 1'b0;
        end else begin
            tmp_78_fu_1394_p4[ap_tvar_int_15] = key[22 - ap_tvar_int_15];
        end
    end
end

integer ap_tvar_int_16;

always @ (key) begin
    for (ap_tvar_int_16 = 2 - 1; ap_tvar_int_16 >= 0; ap_tvar_int_16 = ap_tvar_int_16 - 1) begin
        if (ap_tvar_int_16 > 34 - 33) begin
            tmp_79_fu_1496_p4[ap_tvar_int_16] = 1'b0;
        end else begin
            tmp_79_fu_1496_p4[ap_tvar_int_16] = key[34 - ap_tvar_int_16];
        end
    end
end

assign tmp_7_fu_210_p3 = key[32'd63];

integer ap_tvar_int_17;

always @ (key) begin
    for (ap_tvar_int_17 = 2 - 1; ap_tvar_int_17 >= 0; ap_tvar_int_17 = ap_tvar_int_17 - 1) begin
        if (ap_tvar_int_17 > 13 - 12) begin
            tmp_80_fu_1506_p4[ap_tvar_int_17] = 1'b0;
        end else begin
            tmp_80_fu_1506_p4[ap_tvar_int_17] = key[13 - ap_tvar_int_17];
        end
    end
end

integer ap_tvar_int_18;

always @ (key) begin
    for (ap_tvar_int_18 = 2 - 1; ap_tvar_int_18 >= 0; ap_tvar_int_18 = ap_tvar_int_18 - 1) begin
        if (ap_tvar_int_18 > 38 - 37) begin
            tmp_81_fu_1516_p4[ap_tvar_int_18] = 1'b0;
        end else begin
            tmp_81_fu_1516_p4[ap_tvar_int_18] = key[38 - ap_tvar_int_18];
        end
    end
end

integer ap_tvar_int_19;

always @ (key) begin
    for (ap_tvar_int_19 = 2 - 1; ap_tvar_int_19 >= 0; ap_tvar_int_19 = ap_tvar_int_19 - 1) begin
        if (ap_tvar_int_19 > 42 - 41) begin
            tmp_82_fu_1620_p4[ap_tvar_int_19] = 1'b0;
        end else begin
            tmp_82_fu_1620_p4[ap_tvar_int_19] = key[42 - ap_tvar_int_19];
        end
    end
end

integer ap_tvar_int_20;

always @ (key) begin
    for (ap_tvar_int_20 = 2 - 1; ap_tvar_int_20 >= 0; ap_tvar_int_20 = ap_tvar_int_20 - 1) begin
        if (ap_tvar_int_20 > 21 - 20) begin
            tmp_83_fu_1630_p4[ap_tvar_int_20] = 1'b0;
        end else begin
            tmp_83_fu_1630_p4[ap_tvar_int_20] = key[21 - ap_tvar_int_20];
        end
    end
end

integer ap_tvar_int_21;

always @ (key) begin
    for (ap_tvar_int_21 = 2 - 1; ap_tvar_int_21 >= 0; ap_tvar_int_21 = ap_tvar_int_21 - 1) begin
        if (ap_tvar_int_21 > 58 - 57) begin
            tmp_84_fu_1732_p4[ap_tvar_int_21] = 1'b0;
        end else begin
            tmp_84_fu_1732_p4[ap_tvar_int_21] = key[58 - ap_tvar_int_21];
        end
    end
end

integer ap_tvar_int_22;

always @ (key) begin
    for (ap_tvar_int_22 = 2 - 1; ap_tvar_int_22 >= 0; ap_tvar_int_22 = ap_tvar_int_22 - 1) begin
        if (ap_tvar_int_22 > 11 - 10) begin
            tmp_85_fu_1836_p4[ap_tvar_int_22] = 1'b0;
        end else begin
            tmp_85_fu_1836_p4[ap_tvar_int_22] = key[11 - ap_tvar_int_22];
        end
    end
end

integer ap_tvar_int_23;

always @ (key) begin
    for (ap_tvar_int_23 = 2 - 1; ap_tvar_int_23 >= 0; ap_tvar_int_23 = ap_tvar_int_23 - 1) begin
        if (ap_tvar_int_23 > 50 - 49) begin
            tmp_86_fu_1940_p4[ap_tvar_int_23] = 1'b0;
        end else begin
            tmp_86_fu_1940_p4[ap_tvar_int_23] = key[50 - ap_tvar_int_23];
        end
    end
end

assign tmp_87_fu_1950_p4 = {{key[7:6]}};

integer ap_tvar_int_24;

always @ (key) begin
    for (ap_tvar_int_24 = 2 - 1; ap_tvar_int_24 >= 0; ap_tvar_int_24 = ap_tvar_int_24 - 1) begin
        if (ap_tvar_int_24 > 29 - 28) begin
            tmp_88_fu_1960_p4[ap_tvar_int_24] = 1'b0;
        end else begin
            tmp_88_fu_1960_p4[ap_tvar_int_24] = key[29 - ap_tvar_int_24];
        end
    end
end

integer ap_tvar_int_25;

always @ (key) begin
    for (ap_tvar_int_25 = 2 - 1; ap_tvar_int_25 >= 0; ap_tvar_int_25 = ap_tvar_int_25 - 1) begin
        if (ap_tvar_int_25 > 27 - 26) begin
            tmp_89_fu_1970_p4[ap_tvar_int_25] = 1'b0;
        end else begin
            tmp_89_fu_1970_p4[ap_tvar_int_25] = key[27 - ap_tvar_int_25];
        end
    end
end

assign tmp_8_fu_218_p3 = key[32'd6];

integer ap_tvar_int_26;

always @ (key) begin
    for (ap_tvar_int_26 = 2 - 1; ap_tvar_int_26 >= 0; ap_tvar_int_26 = ap_tvar_int_26 - 1) begin
        if (ap_tvar_int_26 > 3 - 2) begin
            tmp_90_fu_2072_p4[ap_tvar_int_26] = 1'b0;
        end else begin
            tmp_90_fu_2072_p4[ap_tvar_int_26] = key[3 - ap_tvar_int_26];
        end
    end
end

assign tmp_91_fu_2082_p4 = {{key[23:22]}};

integer ap_tvar_int_27;

always @ (key) begin
    for (ap_tvar_int_27 = 2 - 1; ap_tvar_int_27 >= 0; ap_tvar_int_27 = ap_tvar_int_27 - 1) begin
        if (ap_tvar_int_27 > 43 - 42) begin
            tmp_92_fu_2092_p4[ap_tvar_int_27] = 1'b0;
        end else begin
            tmp_92_fu_2092_p4[ap_tvar_int_27] = key[43 - ap_tvar_int_27];
        end
    end
end

assign tmp_93_fu_2196_p4 = {{key[39:38]}};

integer ap_tvar_int_28;

always @ (key) begin
    for (ap_tvar_int_28 = 2 - 1; ap_tvar_int_28 >= 0; ap_tvar_int_28 = ap_tvar_int_28 - 1) begin
        if (ap_tvar_int_28 > 19 - 18) begin
            tmp_94_fu_2206_p4[ap_tvar_int_28] = 1'b0;
        end else begin
            tmp_94_fu_2206_p4[ap_tvar_int_28] = key[19 - ap_tvar_int_28];
        end
    end
end

assign tmp_95_fu_2308_p4 = {{key[55:54]}};

integer ap_tvar_int_29;

always @ (key) begin
    for (ap_tvar_int_29 = 2 - 1; ap_tvar_int_29 >= 0; ap_tvar_int_29 = ap_tvar_int_29 - 1) begin
        if (ap_tvar_int_29 > 35 - 34) begin
            tmp_96_fu_2318_p4[ap_tvar_int_29] = 1'b0;
        end else begin
            tmp_96_fu_2318_p4[ap_tvar_int_29] = key[35 - ap_tvar_int_29];
        end
    end
end

assign tmp_97_fu_2422_p4 = {{key[63:62]}};

integer ap_tvar_int_30;

always @ (key) begin
    for (ap_tvar_int_30 = 2 - 1; ap_tvar_int_30 >= 0; ap_tvar_int_30 = ap_tvar_int_30 - 1) begin
        if (ap_tvar_int_30 > 31 - 30) begin
            tmp_98_fu_2432_p4[ap_tvar_int_30] = 1'b0;
        end else begin
            tmp_98_fu_2432_p4[ap_tvar_int_30] = key[31 - ap_tvar_int_30];
        end
    end
end

assign tmp_9_fu_226_p3 = key[32'd14];

assign tmp_fu_154_p3 = key[32'd7];

assign tmp_s_fu_602_p4 = {{key[6:5]}};

assign ap_return_0 = subkey_fu_632_p46;

assign ap_return_1 = subkey_1_fu_766_p45;

assign ap_return_10 = subkey_10_fu_1846_p46;

assign ap_return_11 = subkey_11_fu_1980_p45;

assign ap_return_12 = subkey_12_fu_2102_p46;

assign ap_return_13 = subkey_13_fu_2216_p45;

assign ap_return_14 = subkey_14_fu_2328_p46;

assign ap_return_15 = subkey_15_fu_2442_p46;

assign ap_return_2 = subkey_2_fu_888_p46;

assign ap_return_3 = subkey_3_fu_1012_p45;

assign ap_return_4 = subkey_4_fu_1144_p44;

assign ap_return_5 = subkey_5_fu_1274_p44;

assign ap_return_6 = subkey_6_fu_1404_p45;

assign ap_return_7 = subkey_7_fu_1526_p46;

assign ap_return_8 = subkey_8_fu_1640_p45;

assign ap_return_9 = subkey_9_fu_1742_p46;

endmodule //des_encrypt_generate_subkeys
