

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1"],
		"CDFG" : "chacha20_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "53", "EstimateLatencyMax" : "53",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "state_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "state_15", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"}]}
