-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity des_encrypt_generate_subkeys is
port (
    ap_ready : OUT STD_LOGIC;
    key : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of des_encrypt_generate_subkeys is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal tmp_14_fu_266_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_290_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_242_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_346_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_162_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_194_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_178_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_154_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_274_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_202_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_322_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_234_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_338_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_306_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_612_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_26_fu_362_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_602_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_210_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_314_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_258_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_170_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_482_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_570_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_402_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_fu_450_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_530_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_100_fu_594_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_394_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_474_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_562_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_514_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_418_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_538_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_506_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_546_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_466_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_378_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_426_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_fu_578_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_46_fu_522_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_fu_622_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_36_fu_442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_386_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_250_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_186_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_282_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_330_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_736_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_57_fu_726_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_59_fu_746_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_42_fu_490_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_458_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_554_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_434_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_586_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_fu_756_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_226_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_fu_868_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_61_fu_858_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_63_fu_878_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_43_fu_498_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_fu_1002_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_64_fu_982_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_65_fu_992_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_69_fu_1124_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_67_fu_1104_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_70_fu_1134_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_68_fu_1114_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_73_fu_1254_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_72_fu_1244_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_74_fu_1264_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_71_fu_1234_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_77_fu_1384_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_76_fu_1374_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_78_fu_1394_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_75_fu_1364_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_80_fu_1506_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_81_fu_1516_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_79_fu_1496_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_83_fu_1630_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_82_fu_1620_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_84_fu_1732_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_85_fu_1836_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_87_fu_1950_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_88_fu_1960_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_89_fu_1970_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_86_fu_1940_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_91_fu_2082_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_92_fu_2092_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_90_fu_2072_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_93_fu_2196_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_94_fu_2206_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_95_fu_2308_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_96_fu_2318_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_98_fu_2432_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_97_fu_2422_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal subkey_fu_632_p46 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_1_fu_766_p45 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_2_fu_888_p46 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_3_fu_1012_p45 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_4_fu_1144_p44 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_5_fu_1274_p44 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_6_fu_1404_p45 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_7_fu_1526_p46 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_8_fu_1640_p45 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_9_fu_1742_p46 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_10_fu_1846_p46 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_11_fu_1980_p45 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_12_fu_2102_p46 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_13_fu_2216_p45 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_14_fu_2328_p46 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkey_15_fu_2442_p46 : STD_LOGIC_VECTOR (47 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= subkey_fu_632_p46;
    ap_return_1 <= subkey_1_fu_766_p45;
    ap_return_10 <= subkey_10_fu_1846_p46;
    ap_return_11 <= subkey_11_fu_1980_p45;
    ap_return_12 <= subkey_12_fu_2102_p46;
    ap_return_13 <= subkey_13_fu_2216_p45;
    ap_return_14 <= subkey_14_fu_2328_p46;
    ap_return_15 <= subkey_15_fu_2442_p46;
    ap_return_2 <= subkey_2_fu_888_p46;
    ap_return_3 <= subkey_3_fu_1012_p45;
    ap_return_4 <= subkey_4_fu_1144_p44;
    ap_return_5 <= subkey_5_fu_1274_p44;
    ap_return_6 <= subkey_6_fu_1404_p45;
    ap_return_7 <= subkey_7_fu_1526_p46;
    ap_return_8 <= subkey_8_fu_1640_p45;
    ap_return_9 <= subkey_9_fu_1742_p46;
    subkey_10_fu_1846_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_4_fu_186_p3 & tmp_7_fu_210_p3) & tmp_1_fu_162_p3) & tmp_14_fu_266_p3) & tmp_19_fu_306_p3) & tmp_23_fu_338_p3) & tmp_21_fu_322_p3) & tmp_18_fu_298_p3) & tmp_5_fu_194_p3) & tmp_24_fu_346_p3) & tmp_11_fu_242_p3) & tmp_fu_154_p3) & tmp_13_fu_258_p3) & tmp_9_fu_226_p3) & tmp_2_fu_170_p3) & tmp_22_fu_330_p3) & tmp_16_fu_282_p3) & tmp_26_fu_362_p3) & tmp_6_fu_202_p3) & tmp_80_fu_1506_p4) & tmp_10_fu_234_p3) & tmp_3_fu_178_p3) & tmp_20_fu_314_p3) & tmp_31_fu_402_p3) & tmp_42_fu_490_p3) & tmp_49_fu_546_p3) & tmp_100_fu_594_p3) & tmp_85_fu_1836_p4) & tmp_48_fu_538_p3) & tmp_30_fu_394_p3) & tmp_41_fu_482_p3) & tmp_35_fu_434_p3) & tmp_51_fu_562_p3) & tmp_38_fu_458_p3) & tmp_34_fu_426_p3) & tmp_39_fu_466_p3) & tmp_29_fu_386_p3) & tmp_46_fu_522_p3) & tmp_52_fu_570_p3) & tmp_43_fu_498_p3) & tmp_36_fu_442_p3) & tmp_79_fu_1496_p4) & tmp_54_fu_586_p3) & tmp_47_fu_530_p3) & tmp_50_fu_554_p3);
    subkey_11_fu_1980_p45 <= (((((((((((((((((((((((((((((((((((((((((((tmp_6_fu_202_p3 & tmp_9_fu_226_p3) & tmp_3_fu_178_p3) & tmp_16_fu_282_p3) & tmp_21_fu_322_p3) & tmp_25_fu_354_p3) & tmp_23_fu_338_p3) & tmp_20_fu_314_p3) & tmp_7_fu_210_p3) & tmp_26_fu_362_p3) & tmp_13_fu_258_p3) & tmp_2_fu_170_p3) & tmp_15_fu_274_p3) & tmp_11_fu_242_p3) & tmp_4_fu_186_p3) & tmp_24_fu_346_p3) & tmp_18_fu_298_p3) & tmp_87_fu_1950_p4) & tmp_88_fu_1960_p4) & tmp_12_fu_250_p3) & tmp_5_fu_194_p3) & tmp_22_fu_330_p3) & tmp_33_fu_418_p3) & tmp_44_fu_506_p3) & tmp_51_fu_562_p3) & tmp_29_fu_386_p3) & tmp_89_fu_1970_p4) & tmp_50_fu_554_p3) & tmp_32_fu_410_p3) & tmp_43_fu_498_p3) & tmp_37_fu_450_p3) & tmp_53_fu_578_p3) & tmp_40_fu_474_p3) & tmp_36_fu_442_p3) & tmp_41_fu_482_p3) & tmp_31_fu_402_p3) & tmp_48_fu_538_p3) & tmp_54_fu_586_p3) & tmp_45_fu_514_p3) & tmp_38_fu_458_p3) & tmp_86_fu_1940_p4) & tmp_28_fu_378_p3) & tmp_49_fu_546_p3) & tmp_52_fu_570_p3);
    subkey_12_fu_2102_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_8_fu_218_p3 & tmp_11_fu_242_p3) & tmp_5_fu_194_p3) & tmp_18_fu_298_p3) & tmp_23_fu_338_p3) & tmp_27_fu_370_p3) & tmp_25_fu_354_p3) & tmp_22_fu_330_p3) & tmp_9_fu_226_p3) & tmp_fu_154_p3) & tmp_15_fu_274_p3) & tmp_4_fu_186_p3) & tmp_17_fu_290_p3) & tmp_13_fu_258_p3) & tmp_6_fu_202_p3) & tmp_26_fu_362_p3) & tmp_20_fu_314_p3) & tmp_91_fu_2082_p4) & tmp_1_fu_162_p3) & tmp_21_fu_322_p3) & tmp_14_fu_266_p3) & tmp_7_fu_210_p3) & tmp_24_fu_346_p3) & tmp_35_fu_434_p3) & tmp_46_fu_522_p3) & tmp_53_fu_578_p3) & tmp_31_fu_402_p3) & tmp_92_fu_2092_p4) & tmp_52_fu_570_p3) & tmp_34_fu_426_p3) & tmp_45_fu_514_p3) & tmp_39_fu_466_p3) & tmp_100_fu_594_p3) & tmp_42_fu_490_p3) & tmp_38_fu_458_p3) & tmp_43_fu_498_p3) & tmp_33_fu_418_p3) & tmp_50_fu_554_p3) & tmp_28_fu_378_p3) & tmp_47_fu_530_p3) & tmp_40_fu_474_p3) & tmp_90_fu_2072_p4) & tmp_30_fu_394_p3) & tmp_51_fu_562_p3) & tmp_54_fu_586_p3);
    subkey_13_fu_2216_p45 <= (((((((((((((((((((((((((((((((((((((((((((tmp_10_fu_234_p3 & tmp_13_fu_258_p3) & tmp_7_fu_210_p3) & tmp_20_fu_314_p3) & tmp_25_fu_354_p3) & tmp_1_fu_162_p3) & tmp_27_fu_370_p3) & tmp_24_fu_346_p3) & tmp_11_fu_242_p3) & tmp_2_fu_170_p3) & tmp_17_fu_290_p3) & tmp_6_fu_202_p3) & tmp_19_fu_306_p3) & tmp_15_fu_274_p3) & tmp_59_fu_746_p4) & tmp_22_fu_330_p3) & tmp_93_fu_2196_p4) & tmp_3_fu_178_p3) & tmp_23_fu_338_p3) & tmp_16_fu_282_p3) & tmp_9_fu_226_p3) & tmp_26_fu_362_p3) & tmp_37_fu_450_p3) & tmp_48_fu_538_p3) & tmp_100_fu_594_p3) & tmp_33_fu_418_p3) & tmp_60_fu_756_p4) & tmp_54_fu_586_p3) & tmp_36_fu_442_p3) & tmp_47_fu_530_p3) & tmp_41_fu_482_p3) & tmp_29_fu_386_p3) & tmp_44_fu_506_p3) & tmp_40_fu_474_p3) & tmp_45_fu_514_p3) & tmp_35_fu_434_p3) & tmp_52_fu_570_p3) & tmp_30_fu_394_p3) & tmp_49_fu_546_p3) & tmp_42_fu_490_p3) & tmp_94_fu_2206_p4) & tmp_32_fu_410_p3) & tmp_53_fu_578_p3) & tmp_28_fu_378_p3);
    subkey_14_fu_2328_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_12_fu_250_p3 & tmp_15_fu_274_p3) & tmp_9_fu_226_p3) & tmp_22_fu_330_p3) & tmp_27_fu_370_p3) & tmp_3_fu_178_p3) & tmp_1_fu_162_p3) & tmp_26_fu_362_p3) & tmp_13_fu_258_p3) & tmp_4_fu_186_p3) & tmp_19_fu_306_p3) & tmp_8_fu_218_p3) & tmp_21_fu_322_p3) & tmp_17_fu_290_p3) & tmp_63_fu_878_p4) & tmp_24_fu_346_p3) & tmp_95_fu_2308_p4) & tmp_5_fu_194_p3) & tmp_25_fu_354_p3) & tmp_18_fu_298_p3) & tmp_11_fu_242_p3) & tmp_fu_154_p3) & tmp_39_fu_466_p3) & tmp_50_fu_554_p3) & tmp_29_fu_386_p3) & tmp_35_fu_434_p3) & tmp_45_fu_514_p3) & tmp_53_fu_578_p3) & tmp_28_fu_378_p3) & tmp_38_fu_458_p3) & tmp_49_fu_546_p3) & tmp_43_fu_498_p3) & tmp_31_fu_402_p3) & tmp_46_fu_522_p3) & tmp_42_fu_490_p3) & tmp_47_fu_530_p3) & tmp_37_fu_450_p3) & tmp_54_fu_586_p3) & tmp_32_fu_410_p3) & tmp_51_fu_562_p3) & tmp_44_fu_506_p3) & tmp_96_fu_2318_p4) & tmp_34_fu_426_p3) & tmp_100_fu_594_p3) & tmp_30_fu_394_p3);
    subkey_15_fu_2442_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_13_fu_258_p3 & tmp_16_fu_282_p3) & tmp_10_fu_234_p3) & tmp_23_fu_338_p3) & tmp_fu_154_p3) & tmp_4_fu_186_p3) & tmp_2_fu_170_p3) & tmp_27_fu_370_p3) & tmp_14_fu_266_p3) & tmp_5_fu_194_p3) & tmp_20_fu_314_p3) & tmp_9_fu_226_p3) & tmp_22_fu_330_p3) & tmp_18_fu_298_p3) & tmp_98_fu_2432_p4) & tmp_25_fu_354_p3) & tmp_97_fu_2422_p4) & tmp_6_fu_202_p3) & tmp_26_fu_362_p3) & tmp_19_fu_306_p3) & tmp_12_fu_250_p3) & tmp_1_fu_162_p3) & tmp_40_fu_474_p3) & tmp_51_fu_562_p3) & tmp_30_fu_394_p3) & tmp_36_fu_442_p3) & tmp_46_fu_522_p3) & tmp_54_fu_586_p3) & tmp_29_fu_386_p3) & tmp_39_fu_466_p3) & tmp_50_fu_554_p3) & tmp_44_fu_506_p3) & tmp_32_fu_410_p3) & tmp_47_fu_530_p3) & tmp_43_fu_498_p3) & tmp_48_fu_538_p3) & tmp_38_fu_458_p3) & tmp_100_fu_594_p3) & tmp_33_fu_418_p3) & tmp_52_fu_570_p3) & tmp_45_fu_514_p3) & tmp_92_fu_2092_p4) & tmp_35_fu_434_p3) & tmp_28_fu_378_p3) & tmp_31_fu_402_p3);
    subkey_1_fu_766_p45 <= (((((((((((((((((((((((((((((((((((((((((((tmp_15_fu_274_p3 & tmp_18_fu_298_p3) & tmp_12_fu_250_p3) & tmp_25_fu_354_p3) & tmp_2_fu_170_p3) & tmp_6_fu_202_p3) & tmp_4_fu_186_p3) & tmp_1_fu_162_p3) & tmp_16_fu_282_p3) & tmp_7_fu_210_p3) & tmp_22_fu_330_p3) & tmp_11_fu_242_p3) & tmp_24_fu_346_p3) & tmp_20_fu_314_p3) & tmp_58_fu_736_p4) & tmp_27_fu_370_p3) & tmp_57_fu_726_p4) & tmp_59_fu_746_p4) & tmp_21_fu_322_p3) & tmp_14_fu_266_p3) & tmp_3_fu_178_p3) & tmp_42_fu_490_p3) & tmp_53_fu_578_p3) & tmp_32_fu_410_p3) & tmp_38_fu_458_p3) & tmp_48_fu_538_p3) & tmp_28_fu_378_p3) & tmp_31_fu_402_p3) & tmp_41_fu_482_p3) & tmp_52_fu_570_p3) & tmp_46_fu_522_p3) & tmp_34_fu_426_p3) & tmp_49_fu_546_p3) & tmp_45_fu_514_p3) & tmp_50_fu_554_p3) & tmp_40_fu_474_p3) & tmp_29_fu_386_p3) & tmp_35_fu_434_p3) & tmp_54_fu_586_p3) & tmp_47_fu_530_p3) & tmp_60_fu_756_p4) & tmp_37_fu_450_p3) & tmp_30_fu_394_p3) & tmp_33_fu_418_p3);
    subkey_2_fu_888_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_17_fu_290_p3 & tmp_20_fu_314_p3) & tmp_14_fu_266_p3) & tmp_27_fu_370_p3) & tmp_4_fu_186_p3) & tmp_8_fu_218_p3) & tmp_6_fu_202_p3) & tmp_3_fu_178_p3) & tmp_18_fu_298_p3) & tmp_9_fu_226_p3) & tmp_24_fu_346_p3) & tmp_13_fu_258_p3) & tmp_26_fu_362_p3) & tmp_22_fu_330_p3) & tmp_62_fu_868_p4) & tmp_1_fu_162_p3) & tmp_61_fu_858_p4) & tmp_63_fu_878_p4) & tmp_23_fu_338_p3) & tmp_16_fu_282_p3) & tmp_5_fu_194_p3) & tmp_44_fu_506_p3) & tmp_100_fu_594_p3) & tmp_34_fu_426_p3) & tmp_40_fu_474_p3) & tmp_50_fu_554_p3) & tmp_30_fu_394_p3) & tmp_33_fu_418_p3) & tmp_43_fu_498_p3) & tmp_54_fu_586_p3) & tmp_48_fu_538_p3) & tmp_36_fu_442_p3) & tmp_51_fu_562_p3) & tmp_47_fu_530_p3) & tmp_52_fu_570_p3) & tmp_42_fu_490_p3) & tmp_31_fu_402_p3) & tmp_37_fu_450_p3) & tmp_28_fu_378_p3) & tmp_49_fu_546_p3) & tmp_45_fu_514_p3) & tmp_53_fu_578_p3) & tmp_39_fu_466_p3) & tmp_32_fu_410_p3) & tmp_35_fu_434_p3);
    subkey_3_fu_1012_p45 <= (((((((((((((((((((((((((((((((((((((((((((tmp_19_fu_306_p3 & tmp_22_fu_330_p3) & tmp_16_fu_282_p3) & tmp_1_fu_162_p3) & tmp_6_fu_202_p3) & tmp_10_fu_234_p3) & tmp_8_fu_218_p3) & tmp_5_fu_194_p3) & tmp_20_fu_314_p3) & tmp_11_fu_242_p3) & tmp_26_fu_362_p3) & tmp_15_fu_274_p3) & tmp_fu_154_p3) & tmp_24_fu_346_p3) & tmp_66_fu_1002_p4) & tmp_3_fu_178_p3) & tmp_64_fu_982_p4) & tmp_55_fu_612_p4) & tmp_25_fu_354_p3) & tmp_18_fu_298_p3) & tmp_7_fu_210_p3) & tmp_46_fu_522_p3) & tmp_29_fu_386_p3) & tmp_36_fu_442_p3) & tmp_42_fu_490_p3) & tmp_52_fu_570_p3) & tmp_32_fu_410_p3) & tmp_35_fu_434_p3) & tmp_45_fu_514_p3) & tmp_28_fu_378_p3) & tmp_50_fu_554_p3) & tmp_38_fu_458_p3) & tmp_65_fu_992_p4) & tmp_54_fu_586_p3) & tmp_44_fu_506_p3) & tmp_33_fu_418_p3) & tmp_39_fu_466_p3) & tmp_30_fu_394_p3) & tmp_51_fu_562_p3) & tmp_47_fu_530_p3) & tmp_100_fu_594_p3) & tmp_41_fu_482_p3) & tmp_34_fu_426_p3) & tmp_37_fu_450_p3);
    subkey_4_fu_1144_p44 <= ((((((((((((((((((((((((((((((((((((((((((tmp_21_fu_322_p3 & tmp_24_fu_346_p3) & tmp_18_fu_298_p3) & tmp_3_fu_178_p3) & tmp_8_fu_218_p3) & tmp_12_fu_250_p3) & tmp_10_fu_234_p3) & tmp_7_fu_210_p3) & tmp_22_fu_330_p3) & tmp_13_fu_258_p3) & tmp_fu_154_p3) & tmp_17_fu_290_p3) & tmp_2_fu_170_p3) & tmp_26_fu_362_p3) & tmp_69_fu_1124_p4) & tmp_5_fu_194_p3) & tmp_67_fu_1104_p4) & tmp_70_fu_1134_p4) & tmp_27_fu_370_p3) & tmp_20_fu_314_p3) & tmp_9_fu_226_p3) & tmp_48_fu_538_p3) & tmp_31_fu_402_p3) & tmp_38_fu_458_p3) & tmp_44_fu_506_p3) & tmp_54_fu_586_p3) & tmp_34_fu_426_p3) & tmp_37_fu_450_p3) & tmp_47_fu_530_p3) & tmp_30_fu_394_p3) & tmp_52_fu_570_p3) & tmp_40_fu_474_p3) & tmp_68_fu_1114_p4) & tmp_28_fu_378_p3) & tmp_46_fu_522_p3) & tmp_35_fu_434_p3) & tmp_41_fu_482_p3) & tmp_32_fu_410_p3) & tmp_65_fu_992_p4) & tmp_29_fu_386_p3) & tmp_43_fu_498_p3) & tmp_36_fu_442_p3) & tmp_39_fu_466_p3);
    subkey_5_fu_1274_p44 <= ((((((((((((((((((((((((((((((((((((((((((tmp_23_fu_338_p3 & tmp_26_fu_362_p3) & tmp_20_fu_314_p3) & tmp_5_fu_194_p3) & tmp_10_fu_234_p3) & tmp_14_fu_266_p3) & tmp_12_fu_250_p3) & tmp_9_fu_226_p3) & tmp_24_fu_346_p3) & tmp_15_fu_274_p3) & tmp_2_fu_170_p3) & tmp_19_fu_306_p3) & tmp_4_fu_186_p3) & tmp_fu_154_p3) & tmp_73_fu_1254_p4) & tmp_7_fu_210_p3) & tmp_72_fu_1244_p4) & tmp_74_fu_1264_p4) & tmp_1_fu_162_p3) & tmp_22_fu_330_p3) & tmp_11_fu_242_p3) & tmp_50_fu_554_p3) & tmp_33_fu_418_p3) & tmp_40_fu_474_p3) & tmp_46_fu_522_p3) & tmp_71_fu_1234_p4) & tmp_39_fu_466_p3) & tmp_49_fu_546_p3) & tmp_32_fu_410_p3) & tmp_54_fu_586_p3) & tmp_42_fu_490_p3) & tmp_29_fu_386_p3) & tmp_53_fu_578_p3) & tmp_30_fu_394_p3) & tmp_48_fu_538_p3) & tmp_37_fu_450_p3) & tmp_43_fu_498_p3) & tmp_34_fu_426_p3) & tmp_68_fu_1114_p4) & tmp_31_fu_402_p3) & tmp_45_fu_514_p3) & tmp_38_fu_458_p3) & tmp_41_fu_482_p3);
    subkey_6_fu_1404_p45 <= (((((((((((((((((((((((((((((((((((((((((((tmp_25_fu_354_p3 & tmp_fu_154_p3) & tmp_22_fu_330_p3) & tmp_7_fu_210_p3) & tmp_12_fu_250_p3) & tmp_16_fu_282_p3) & tmp_14_fu_266_p3) & tmp_11_fu_242_p3) & tmp_26_fu_362_p3) & tmp_17_fu_290_p3) & tmp_4_fu_186_p3) & tmp_21_fu_322_p3) & tmp_6_fu_202_p3) & tmp_2_fu_170_p3) & tmp_77_fu_1384_p4) & tmp_9_fu_226_p3) & tmp_76_fu_1374_p4) & tmp_78_fu_1394_p4) & tmp_3_fu_178_p3) & tmp_24_fu_346_p3) & tmp_13_fu_258_p3) & tmp_52_fu_570_p3) & tmp_35_fu_434_p3) & tmp_42_fu_490_p3) & tmp_48_fu_538_p3) & tmp_75_fu_1364_p4) & tmp_41_fu_482_p3) & tmp_51_fu_562_p3) & tmp_34_fu_426_p3) & tmp_28_fu_378_p3) & tmp_44_fu_506_p3) & tmp_31_fu_402_p3) & tmp_100_fu_594_p3) & tmp_32_fu_410_p3) & tmp_50_fu_554_p3) & tmp_39_fu_466_p3) & tmp_45_fu_514_p3) & tmp_36_fu_442_p3) & tmp_29_fu_386_p3) & tmp_53_fu_578_p3) & tmp_33_fu_418_p3) & tmp_47_fu_530_p3) & tmp_40_fu_474_p3) & tmp_43_fu_498_p3);
    subkey_7_fu_1526_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_27_fu_370_p3 & tmp_2_fu_170_p3) & tmp_24_fu_346_p3) & tmp_9_fu_226_p3) & tmp_14_fu_266_p3) & tmp_18_fu_298_p3) & tmp_16_fu_282_p3) & tmp_13_fu_258_p3) & tmp_fu_154_p3) & tmp_19_fu_306_p3) & tmp_6_fu_202_p3) & tmp_23_fu_338_p3) & tmp_8_fu_218_p3) & tmp_4_fu_186_p3) & tmp_80_fu_1506_p4) & tmp_11_fu_242_p3) & tmp_21_fu_322_p3) & tmp_1_fu_162_p3) & tmp_81_fu_1516_p4) & tmp_5_fu_194_p3) & tmp_26_fu_362_p3) & tmp_15_fu_274_p3) & tmp_54_fu_586_p3) & tmp_37_fu_450_p3) & tmp_44_fu_506_p3) & tmp_50_fu_554_p3) & tmp_79_fu_1496_p4) & tmp_43_fu_498_p3) & tmp_53_fu_578_p3) & tmp_36_fu_442_p3) & tmp_30_fu_394_p3) & tmp_46_fu_522_p3) & tmp_33_fu_418_p3) & tmp_29_fu_386_p3) & tmp_34_fu_426_p3) & tmp_52_fu_570_p3) & tmp_41_fu_482_p3) & tmp_47_fu_530_p3) & tmp_38_fu_458_p3) & tmp_31_fu_402_p3) & tmp_100_fu_594_p3) & tmp_35_fu_434_p3) & tmp_49_fu_546_p3) & tmp_42_fu_490_p3) & tmp_45_fu_514_p3);
    subkey_8_fu_1640_p45 <= (((((((((((((((((((((((((((((((((((((((((((tmp_fu_154_p3 & tmp_3_fu_178_p3) & tmp_25_fu_354_p3) & tmp_10_fu_234_p3) & tmp_15_fu_274_p3) & tmp_19_fu_306_p3) & tmp_17_fu_290_p3) & tmp_14_fu_266_p3) & tmp_1_fu_162_p3) & tmp_20_fu_314_p3) & tmp_7_fu_210_p3) & tmp_24_fu_346_p3) & tmp_9_fu_226_p3) & tmp_5_fu_194_p3) & tmp_83_fu_1630_p4) & tmp_12_fu_250_p3) & tmp_22_fu_330_p3) & tmp_2_fu_170_p3) & tmp_73_fu_1254_p4) & tmp_6_fu_202_p3) & tmp_27_fu_370_p3) & tmp_16_fu_282_p3) & tmp_100_fu_594_p3) & tmp_38_fu_458_p3) & tmp_45_fu_514_p3) & tmp_51_fu_562_p3) & tmp_82_fu_1620_p4) & tmp_44_fu_506_p3) & tmp_54_fu_586_p3) & tmp_37_fu_450_p3) & tmp_31_fu_402_p3) & tmp_47_fu_530_p3) & tmp_34_fu_426_p3) & tmp_30_fu_394_p3) & tmp_35_fu_434_p3) & tmp_53_fu_578_p3) & tmp_42_fu_490_p3) & tmp_48_fu_538_p3) & tmp_39_fu_466_p3) & tmp_32_fu_410_p3) & tmp_71_fu_1234_p4) & tmp_50_fu_554_p3) & tmp_43_fu_498_p3) & tmp_46_fu_522_p3);
    subkey_9_fu_1742_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_2_fu_170_p3 & tmp_5_fu_194_p3) & tmp_27_fu_370_p3) & tmp_12_fu_250_p3) & tmp_17_fu_290_p3) & tmp_21_fu_322_p3) & tmp_19_fu_306_p3) & tmp_16_fu_282_p3) & tmp_3_fu_178_p3) & tmp_22_fu_330_p3) & tmp_9_fu_226_p3) & tmp_26_fu_362_p3) & tmp_11_fu_242_p3) & tmp_7_fu_210_p3) & tmp_fu_154_p3) & tmp_20_fu_314_p3) & tmp_14_fu_266_p3) & tmp_24_fu_346_p3) & tmp_4_fu_186_p3) & tmp_77_fu_1384_p4) & tmp_8_fu_218_p3) & tmp_1_fu_162_p3) & tmp_18_fu_298_p3) & tmp_29_fu_386_p3) & tmp_40_fu_474_p3) & tmp_47_fu_530_p3) & tmp_53_fu_578_p3) & tmp_84_fu_1732_p4) & tmp_46_fu_522_p3) & tmp_28_fu_378_p3) & tmp_39_fu_466_p3) & tmp_33_fu_418_p3) & tmp_49_fu_546_p3) & tmp_36_fu_442_p3) & tmp_32_fu_410_p3) & tmp_37_fu_450_p3) & tmp_100_fu_594_p3) & tmp_44_fu_506_p3) & tmp_50_fu_554_p3) & tmp_41_fu_482_p3) & tmp_34_fu_426_p3) & tmp_75_fu_1364_p4) & tmp_52_fu_570_p3) & tmp_45_fu_514_p3) & tmp_48_fu_538_p3);
    subkey_fu_632_p46 <= ((((((((((((((((((((((((((((((((((((((((((((tmp_14_fu_266_p3 & tmp_17_fu_290_p3) & tmp_11_fu_242_p3) & tmp_24_fu_346_p3) & tmp_1_fu_162_p3) & tmp_5_fu_194_p3) & tmp_3_fu_178_p3) & tmp_fu_154_p3) & tmp_15_fu_274_p3) & tmp_6_fu_202_p3) & tmp_21_fu_322_p3) & tmp_10_fu_234_p3) & tmp_23_fu_338_p3) & tmp_19_fu_306_p3) & tmp_55_fu_612_p4) & tmp_26_fu_362_p3) & tmp_s_fu_602_p4) & tmp_7_fu_210_p3) & tmp_27_fu_370_p3) & tmp_20_fu_314_p3) & tmp_13_fu_258_p3) & tmp_2_fu_170_p3) & tmp_41_fu_482_p3) & tmp_52_fu_570_p3) & tmp_31_fu_402_p3) & tmp_37_fu_450_p3) & tmp_47_fu_530_p3) & tmp_100_fu_594_p3) & tmp_30_fu_394_p3) & tmp_40_fu_474_p3) & tmp_51_fu_562_p3) & tmp_45_fu_514_p3) & tmp_33_fu_418_p3) & tmp_48_fu_538_p3) & tmp_44_fu_506_p3) & tmp_49_fu_546_p3) & tmp_39_fu_466_p3) & tmp_28_fu_378_p3) & tmp_34_fu_426_p3) & tmp_53_fu_578_p3) & tmp_46_fu_522_p3) & tmp_56_fu_622_p4) & tmp_36_fu_442_p3) & tmp_29_fu_386_p3) & tmp_32_fu_410_p3);
    tmp_100_fu_594_p3 <= key(60 downto 60);
    tmp_10_fu_234_p3 <= key(22 downto 22);
    tmp_11_fu_242_p3 <= key(30 downto 30);
    tmp_12_fu_250_p3 <= key(38 downto 38);
    tmp_13_fu_258_p3 <= key(46 downto 46);
    tmp_14_fu_266_p3 <= key(54 downto 54);
    tmp_15_fu_274_p3 <= key(62 downto 62);
    tmp_16_fu_282_p3 <= key(5 downto 5);
    tmp_17_fu_290_p3 <= key(13 downto 13);
    tmp_18_fu_298_p3 <= key(21 downto 21);
    tmp_19_fu_306_p3 <= key(29 downto 29);
    tmp_1_fu_162_p3 <= key(15 downto 15);
    tmp_20_fu_314_p3 <= key(37 downto 37);
    tmp_21_fu_322_p3 <= key(45 downto 45);
    tmp_22_fu_330_p3 <= key(53 downto 53);
    tmp_23_fu_338_p3 <= key(61 downto 61);
    tmp_24_fu_346_p3 <= key(4 downto 4);
    tmp_25_fu_354_p3 <= key(12 downto 12);
    tmp_26_fu_362_p3 <= key(20 downto 20);
    tmp_27_fu_370_p3 <= key(28 downto 28);
    tmp_28_fu_378_p3 <= key(1 downto 1);
    tmp_29_fu_386_p3 <= key(9 downto 9);
    tmp_2_fu_170_p3 <= key(23 downto 23);
    tmp_30_fu_394_p3 <= key(17 downto 17);
    tmp_31_fu_402_p3 <= key(25 downto 25);
    tmp_32_fu_410_p3 <= key(33 downto 33);
    tmp_33_fu_418_p3 <= key(41 downto 41);
    tmp_34_fu_426_p3 <= key(49 downto 49);
    tmp_35_fu_434_p3 <= key(57 downto 57);
    tmp_36_fu_442_p3 <= key(2 downto 2);
    tmp_37_fu_450_p3 <= key(10 downto 10);
    tmp_38_fu_458_p3 <= key(18 downto 18);
    tmp_39_fu_466_p3 <= key(26 downto 26);
    tmp_3_fu_178_p3 <= key(31 downto 31);
    tmp_40_fu_474_p3 <= key(34 downto 34);
    tmp_41_fu_482_p3 <= key(42 downto 42);
    tmp_42_fu_490_p3 <= key(50 downto 50);
    tmp_43_fu_498_p3 <= key(58 downto 58);
    tmp_44_fu_506_p3 <= key(3 downto 3);
    tmp_45_fu_514_p3 <= key(11 downto 11);
    tmp_46_fu_522_p3 <= key(19 downto 19);
    tmp_47_fu_530_p3 <= key(27 downto 27);
    tmp_48_fu_538_p3 <= key(35 downto 35);
    tmp_49_fu_546_p3 <= key(43 downto 43);
    tmp_4_fu_186_p3 <= key(39 downto 39);
    tmp_50_fu_554_p3 <= key(51 downto 51);
    tmp_51_fu_562_p3 <= key(59 downto 59);
    tmp_52_fu_570_p3 <= key(36 downto 36);
    tmp_53_fu_578_p3 <= key(44 downto 44);
    tmp_54_fu_586_p3 <= key(52 downto 52);
    
    tmp_55_fu_612_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_55_fu_612_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_27(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_26(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_26(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_27(6-1 downto 0)));
            for tmp_55_fu_612_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_55_fu_612_p4_i) := key(64-1-tmp_55_fu_612_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_55_fu_612_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_56_fu_622_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_56_fu_622_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_33(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_32(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_32(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_33(6-1 downto 0)));
            for tmp_56_fu_622_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_56_fu_622_p4_i) := key(64-1-tmp_56_fu_622_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_56_fu_622_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_57_fu_726_p4 <= key(14 downto 13);
    
    tmp_58_fu_736_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_58_fu_736_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_2F(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_2E(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2E(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2F(6-1 downto 0)));
            for tmp_58_fu_736_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_58_fu_736_p4_i) := key(64-1-tmp_58_fu_736_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_58_fu_736_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_59_fu_746_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_59_fu_746_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_7(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_6(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_6(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_7(6-1 downto 0)));
            for tmp_59_fu_746_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_59_fu_746_p4_i) := key(64-1-tmp_59_fu_746_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_59_fu_746_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_5_fu_194_p3 <= key(47 downto 47);
    
    tmp_60_fu_756_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_60_fu_756_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_3B(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_3A(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3A(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3B(6-1 downto 0)));
            for tmp_60_fu_756_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_60_fu_756_p4_i) := key(64-1-tmp_60_fu_756_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_60_fu_756_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_61_fu_858_p4 <= key(30 downto 29);
    
    tmp_62_fu_868_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_62_fu_868_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_3F(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_3E(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3E(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3F(6-1 downto 0)));
            for tmp_62_fu_868_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_62_fu_868_p4_i) := key(64-1-tmp_62_fu_868_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_62_fu_868_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_63_fu_878_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_63_fu_878_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_17(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_16(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_16(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_17(6-1 downto 0)));
            for tmp_63_fu_878_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_63_fu_878_p4_i) := key(64-1-tmp_63_fu_878_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_63_fu_878_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_64_fu_982_p4 <= key(46 downto 45);
    tmp_65_fu_992_p4 <= key(44 downto 43);
    
    tmp_66_fu_1002_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_66_fu_1002_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_E(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_D(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_D(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_E(6-1 downto 0)));
            for tmp_66_fu_1002_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_66_fu_1002_p4_i) := key(64-1-tmp_66_fu_1002_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_66_fu_1002_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_67_fu_1104_p4 <= key(62 downto 61);
    tmp_68_fu_1114_p4 <= key(60 downto 59);
    
    tmp_69_fu_1124_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_69_fu_1124_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_1E(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_1D(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1D(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1E(6-1 downto 0)));
            for tmp_69_fu_1124_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_69_fu_1124_p4_i) := key(64-1-tmp_69_fu_1124_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_69_fu_1124_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_6_fu_202_p3 <= key(55 downto 55);
    
    tmp_70_fu_1134_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_70_fu_1134_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_37(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_36(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_36(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_37(6-1 downto 0)));
            for tmp_70_fu_1134_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_70_fu_1134_p4_i) := key(64-1-tmp_70_fu_1134_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_70_fu_1134_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_71_fu_1234_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_71_fu_1234_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_2(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_1(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2(6-1 downto 0)));
            for tmp_71_fu_1234_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_71_fu_1234_p4_i) := key(64-1-tmp_71_fu_1234_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_71_fu_1234_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_72_fu_1244_p4 <= key(13 downto 12);
    
    tmp_73_fu_1254_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_73_fu_1254_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_2E(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_2D(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2D(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2E(6-1 downto 0)));
            for tmp_73_fu_1254_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_73_fu_1254_p4_i) := key(64-1-tmp_73_fu_1254_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_73_fu_1254_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_74_fu_1264_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_74_fu_1264_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_6(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_5(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_5(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_6(6-1 downto 0)));
            for tmp_74_fu_1264_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_74_fu_1264_p4_i) := key(64-1-tmp_74_fu_1264_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_74_fu_1264_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_75_fu_1364_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_75_fu_1364_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_12(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_11(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_11(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_12(6-1 downto 0)));
            for tmp_75_fu_1364_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_75_fu_1364_p4_i) := key(64-1-tmp_75_fu_1364_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_75_fu_1364_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_76_fu_1374_p4 <= key(29 downto 28);
    
    tmp_77_fu_1384_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_77_fu_1384_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_3E(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_3D(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3D(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3E(6-1 downto 0)));
            for tmp_77_fu_1384_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_77_fu_1384_p4_i) := key(64-1-tmp_77_fu_1384_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_77_fu_1384_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_78_fu_1394_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_78_fu_1394_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_16(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_15(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_15(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_16(6-1 downto 0)));
            for tmp_78_fu_1394_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_78_fu_1394_p4_i) := key(64-1-tmp_78_fu_1394_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_78_fu_1394_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_79_fu_1496_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_79_fu_1496_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_22(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_21(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_21(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_22(6-1 downto 0)));
            for tmp_79_fu_1496_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_79_fu_1496_p4_i) := key(64-1-tmp_79_fu_1496_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_79_fu_1496_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_7_fu_210_p3 <= key(63 downto 63);
    
    tmp_80_fu_1506_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_80_fu_1506_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_D(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_C(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_C(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_D(6-1 downto 0)));
            for tmp_80_fu_1506_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_80_fu_1506_p4_i) := key(64-1-tmp_80_fu_1506_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_80_fu_1506_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_81_fu_1516_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_81_fu_1516_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_26(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_25(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_25(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_26(6-1 downto 0)));
            for tmp_81_fu_1516_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_81_fu_1516_p4_i) := key(64-1-tmp_81_fu_1516_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_81_fu_1516_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_82_fu_1620_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_82_fu_1620_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_2A(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_29(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_29(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2A(6-1 downto 0)));
            for tmp_82_fu_1620_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_82_fu_1620_p4_i) := key(64-1-tmp_82_fu_1620_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_82_fu_1620_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_83_fu_1630_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_83_fu_1630_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_15(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_14(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_14(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_15(6-1 downto 0)));
            for tmp_83_fu_1630_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_83_fu_1630_p4_i) := key(64-1-tmp_83_fu_1630_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_83_fu_1630_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_84_fu_1732_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_84_fu_1732_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_3A(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_39(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_39(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3A(6-1 downto 0)));
            for tmp_84_fu_1732_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_84_fu_1732_p4_i) := key(64-1-tmp_84_fu_1732_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_84_fu_1732_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_85_fu_1836_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_85_fu_1836_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_B(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_A(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_A(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_B(6-1 downto 0)));
            for tmp_85_fu_1836_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_85_fu_1836_p4_i) := key(64-1-tmp_85_fu_1836_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_85_fu_1836_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_86_fu_1940_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_86_fu_1940_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_32(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_31(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_31(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_32(6-1 downto 0)));
            for tmp_86_fu_1940_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_86_fu_1940_p4_i) := key(64-1-tmp_86_fu_1940_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_86_fu_1940_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_87_fu_1950_p4 <= key(7 downto 6);
    
    tmp_88_fu_1960_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_88_fu_1960_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_1D(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_1C(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1C(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1D(6-1 downto 0)));
            for tmp_88_fu_1960_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_88_fu_1960_p4_i) := key(64-1-tmp_88_fu_1960_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_88_fu_1960_p4 <= resvalue(2-1 downto 0);
    end process;

    
    tmp_89_fu_1970_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_89_fu_1970_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_1B(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_1A(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1A(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1B(6-1 downto 0)));
            for tmp_89_fu_1970_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_89_fu_1970_p4_i) := key(64-1-tmp_89_fu_1970_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_89_fu_1970_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_8_fu_218_p3 <= key(6 downto 6);
    
    tmp_90_fu_2072_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_90_fu_2072_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_3(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_2(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_3(6-1 downto 0)));
            for tmp_90_fu_2072_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_90_fu_2072_p4_i) := key(64-1-tmp_90_fu_2072_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_90_fu_2072_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_91_fu_2082_p4 <= key(23 downto 22);
    
    tmp_92_fu_2092_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_92_fu_2092_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_2B(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_2A(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2A(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_2B(6-1 downto 0)));
            for tmp_92_fu_2092_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_92_fu_2092_p4_i) := key(64-1-tmp_92_fu_2092_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_92_fu_2092_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_93_fu_2196_p4 <= key(39 downto 38);
    
    tmp_94_fu_2206_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_94_fu_2206_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_13(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_12(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_12(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_13(6-1 downto 0)));
            for tmp_94_fu_2206_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_94_fu_2206_p4_i) := key(64-1-tmp_94_fu_2206_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_94_fu_2206_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_95_fu_2308_p4 <= key(55 downto 54);
    
    tmp_96_fu_2318_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_96_fu_2318_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_23(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_22(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_22(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_23(6-1 downto 0)));
            for tmp_96_fu_2318_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_96_fu_2318_p4_i) := key(64-1-tmp_96_fu_2318_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_96_fu_2318_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_97_fu_2422_p4 <= key(63 downto 62);
    
    tmp_98_fu_2432_p4_proc : process(key)
    variable vlo_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(64+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_98_fu_2432_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(64 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(6 - 1 downto 0) := ap_const_lv32_1F(6 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(6 - 1 downto 0) := ap_const_lv32_1E(6 - 1 downto 0);
        v0_cpy := key;
        if (vlo_cpy(6 - 1 downto 0) > vhi_cpy(6 - 1 downto 0)) then
            vhi_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1E(6-1 downto 0)));
            vlo_cpy(6-1 downto 0) := std_logic_vector(64-1-unsigned(ap_const_lv32_1F(6-1 downto 0)));
            for tmp_98_fu_2432_p4_i in 0 to 64-1 loop
                v0_cpy(tmp_98_fu_2432_p4_i) := key(64-1-tmp_98_fu_2432_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(6-1 downto 0)))));

        section := (others=>'0');
        section(6-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(6-1 downto 0)) - unsigned(vlo_cpy(6-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(64-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_98_fu_2432_p4 <= resvalue(2-1 downto 0);
    end process;

    tmp_9_fu_226_p3 <= key(14 downto 14);
    tmp_fu_154_p3 <= key(7 downto 7);
    tmp_s_fu_602_p4 <= key(6 downto 5);
end behav;
