-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity des_encrypt is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    plaintext : IN STD_LOGIC_VECTOR (63 downto 0);
    key : IN STD_LOGIC_VECTOR (63 downto 0);
    ciphertext : OUT STD_LOGIC_VECTOR (63 downto 0);
    ciphertext_ap_vld : OUT STD_LOGIC );
end;


architecture behav of des_encrypt is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "des_encrypt_des_encrypt,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.723857,HLS_SYN_LAT=16,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1907,HLS_SYN_LUT=36839,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal plaintext_read_reg_162 : STD_LOGIC_VECTOR (63 downto 0);
    signal subkeys_reg_167 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_1_reg_172 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_2_reg_177 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_3_reg_182 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_4_reg_187 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_5_reg_192 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_6_reg_197 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_7_reg_202 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_8_reg_207 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_9_reg_212 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_10_reg_217 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_11_reg_222 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_12_reg_227 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_13_reg_232 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_14_reg_237 : STD_LOGIC_VECTOR (47 downto 0);
    signal subkeys_15_reg_242 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_ready : STD_LOGIC;
    signal call_ret_generate_subkeys_fu_53_ap_return_0 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_1 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_2 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_3 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_4 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_5 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_6 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_7 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_8 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_9 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_10 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_11 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_12 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_13 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_14 : STD_LOGIC_VECTOR (47 downto 0);
    signal call_ret_generate_subkeys_fu_53_ap_return_15 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_des_core_fu_59_ap_start : STD_LOGIC;
    signal grp_des_core_fu_59_ap_done : STD_LOGIC;
    signal grp_des_core_fu_59_ap_idle : STD_LOGIC;
    signal grp_des_core_fu_59_ap_ready : STD_LOGIC;
    signal grp_des_core_fu_59_ap_return : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_des_core_fu_59_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component des_encrypt_generate_subkeys IS
    port (
        ap_ready : OUT STD_LOGIC;
        key : IN STD_LOGIC_VECTOR (63 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (47 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;


    component des_encrypt_des_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r : IN STD_LOGIC_VECTOR (63 downto 0);
        subkeys_0_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_1_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_2_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_3_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_4_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_5_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_6_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_7_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_8_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_9_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_10_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_11_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_12_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_13_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_14_val : IN STD_LOGIC_VECTOR (47 downto 0);
        subkeys_15_val : IN STD_LOGIC_VECTOR (47 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    call_ret_generate_subkeys_fu_53 : component des_encrypt_generate_subkeys
    port map (
        ap_ready => call_ret_generate_subkeys_fu_53_ap_ready,
        key => key,
        ap_return_0 => call_ret_generate_subkeys_fu_53_ap_return_0,
        ap_return_1 => call_ret_generate_subkeys_fu_53_ap_return_1,
        ap_return_2 => call_ret_generate_subkeys_fu_53_ap_return_2,
        ap_return_3 => call_ret_generate_subkeys_fu_53_ap_return_3,
        ap_return_4 => call_ret_generate_subkeys_fu_53_ap_return_4,
        ap_return_5 => call_ret_generate_subkeys_fu_53_ap_return_5,
        ap_return_6 => call_ret_generate_subkeys_fu_53_ap_return_6,
        ap_return_7 => call_ret_generate_subkeys_fu_53_ap_return_7,
        ap_return_8 => call_ret_generate_subkeys_fu_53_ap_return_8,
        ap_return_9 => call_ret_generate_subkeys_fu_53_ap_return_9,
        ap_return_10 => call_ret_generate_subkeys_fu_53_ap_return_10,
        ap_return_11 => call_ret_generate_subkeys_fu_53_ap_return_11,
        ap_return_12 => call_ret_generate_subkeys_fu_53_ap_return_12,
        ap_return_13 => call_ret_generate_subkeys_fu_53_ap_return_13,
        ap_return_14 => call_ret_generate_subkeys_fu_53_ap_return_14,
        ap_return_15 => call_ret_generate_subkeys_fu_53_ap_return_15,
        ap_rst => ap_rst);

    grp_des_core_fu_59 : component des_encrypt_des_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_des_core_fu_59_ap_start,
        ap_done => grp_des_core_fu_59_ap_done,
        ap_idle => grp_des_core_fu_59_ap_idle,
        ap_ready => grp_des_core_fu_59_ap_ready,
        input_r => plaintext_read_reg_162,
        subkeys_0_val => subkeys_reg_167,
        subkeys_1_val => subkeys_1_reg_172,
        subkeys_2_val => subkeys_2_reg_177,
        subkeys_3_val => subkeys_3_reg_182,
        subkeys_4_val => subkeys_4_reg_187,
        subkeys_5_val => subkeys_5_reg_192,
        subkeys_6_val => subkeys_6_reg_197,
        subkeys_7_val => subkeys_7_reg_202,
        subkeys_8_val => subkeys_8_reg_207,
        subkeys_9_val => subkeys_9_reg_212,
        subkeys_10_val => subkeys_10_reg_217,
        subkeys_11_val => subkeys_11_reg_222,
        subkeys_12_val => subkeys_12_reg_227,
        subkeys_13_val => subkeys_13_reg_232,
        subkeys_14_val => subkeys_14_reg_237,
        subkeys_15_val => subkeys_15_reg_242,
        ap_return => grp_des_core_fu_59_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_des_core_fu_59_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_des_core_fu_59_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_des_core_fu_59_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_des_core_fu_59_ap_ready = ap_const_logic_1)) then 
                    grp_des_core_fu_59_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                plaintext_read_reg_162 <= plaintext;
                subkeys_10_reg_217 <= call_ret_generate_subkeys_fu_53_ap_return_10;
                subkeys_11_reg_222 <= call_ret_generate_subkeys_fu_53_ap_return_11;
                subkeys_12_reg_227 <= call_ret_generate_subkeys_fu_53_ap_return_12;
                subkeys_13_reg_232 <= call_ret_generate_subkeys_fu_53_ap_return_13;
                subkeys_14_reg_237 <= call_ret_generate_subkeys_fu_53_ap_return_14;
                subkeys_15_reg_242 <= call_ret_generate_subkeys_fu_53_ap_return_15;
                subkeys_1_reg_172 <= call_ret_generate_subkeys_fu_53_ap_return_1;
                subkeys_2_reg_177 <= call_ret_generate_subkeys_fu_53_ap_return_2;
                subkeys_3_reg_182 <= call_ret_generate_subkeys_fu_53_ap_return_3;
                subkeys_4_reg_187 <= call_ret_generate_subkeys_fu_53_ap_return_4;
                subkeys_5_reg_192 <= call_ret_generate_subkeys_fu_53_ap_return_5;
                subkeys_6_reg_197 <= call_ret_generate_subkeys_fu_53_ap_return_6;
                subkeys_7_reg_202 <= call_ret_generate_subkeys_fu_53_ap_return_7;
                subkeys_8_reg_207 <= call_ret_generate_subkeys_fu_53_ap_return_8;
                subkeys_9_reg_212 <= call_ret_generate_subkeys_fu_53_ap_return_9;
                subkeys_reg_167 <= call_ret_generate_subkeys_fu_53_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_des_core_fu_59_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_des_core_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_des_core_fu_59_ap_done)
    begin
        if ((grp_des_core_fu_59_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_des_core_fu_59_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_des_core_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_des_core_fu_59_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_des_core_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ciphertext <= grp_des_core_fu_59_ap_return;

    ciphertext_ap_vld_assign_proc : process(grp_des_core_fu_59_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_des_core_fu_59_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ciphertext_ap_vld <= ap_const_logic_1;
        else 
            ciphertext_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_des_core_fu_59_ap_start <= grp_des_core_fu_59_ap_start_reg;
end behav;
